namespace ScreenshotTranslationUiTester;

public sealed class AppearanceSettingsDialog : Form
{
    private readonly ApiSettings _value;
    private readonly ComboBox _sizing=new(),_uiMode=new(),_uiFont=new(),_previewMode=new(),_previewFont=new(),_overlayMode=new(),_overlayFont=new(),_background=new();
    private readonly NumericUpDown _fixedW=N(820,10000),_fixedH=N(560,10000),_uiSize=N(7,24),_previewSize=N(7,48),_overlaySize=N(0,48),_opacity=N(0,255);
    public ApiSettings Value=>_value;
    public AppearanceSettingsDialog(ApiSettings settings)
    {
        SuspendLayout();AutoScaleMode=AutoScaleMode.Dpi;AutoScaleDimensions=new SizeF(96,96);
        _value=ApiSettingsSnapshot.Copy(settings); Text="预览、字体与译图设置"; ClientSize=new(760,600); MinimumSize=new(700,540); StartPosition=FormStartPosition.CenterParent;
        var tabs=new DarkTabControl{Dock=DockStyle.Fill}; tabs.TabPages.Add(Page("截图与预览",BuildPreview())); tabs.TabPages.Add(Page("外观",BuildAppearance())); tabs.TabPages.Add(Page("译图",BuildOverlay()));
        var buttons=new DialogActionBar(rightToLeft:true);
        var cancel=new Button{Text=UiStrings.Cancel,DialogResult=DialogResult.Cancel,AutoSize=true,MinimumSize=new Size(100,36)}; var ok=new Button{Text=UiStrings.Ok,DialogResult=DialogResult.OK,AutoSize=true,MinimumSize=new Size(100,36)}; var reset=new Button{Text=UiStrings.ResetDefaults,AutoSize=true,MinimumSize=new Size(140,36)}; reset.Click+=(_,_)=>ResetBaseline(); buttons.Controls.AddRange([cancel,ok,reset]);
        Controls.Add(tabs);Controls.Add(buttons);AcceptButton=ok;CancelButton=cancel;FormClosing+=(s,e)=>{if(DialogResult==DialogResult.OK)Commit();}; Initialize();FontManager.ApplyUi(this,_value);UiDarkTheme.Apply(this);
        DialogLayout.Attach(this);ResumeLayout(true);
    }
    private Control BuildPreview(){var t=Table();Row(t,"Preview 窗口大小",_sizing);Row(t,"固定宽度 / 高度",Stack(_fixedW,_fixedH));Row(t,"说明",Info("自动适应：按当前图片和屏幕计算；沿用上次：继承上一 Preview 的最终位置、普通窗口大小和最大化状态；固定大小：使用指定宽高。"));return t;}
    private Control BuildAppearance(){var t=Table();Row(t,"软件界面字体模式",_uiMode);Row(t,"界面字体 / 大小",Stack(_uiFont,_uiSize));Row(t,"Preview 右侧字体模式",_previewMode);Row(t,"Preview 字体 / 大小",Stack(_previewFont,_previewSize));Row(t,"字体状态",Info(string.Join("　",new[]{"Microsoft YaHei UI","Segoe UI","Noto Sans CJK SC"}.Select(x=>$"{x}：{(FontSettingsPolicy.IsInstalled(x)?"已安装":"未安装")}"))));return t;}
    private Control BuildOverlay(){var t=Table();Row(t,"译图字体模式",_overlayMode);Row(t,"译图字体",_overlayFont);Row(t,"译图字号",Stack(_overlaySize,Info("0 表示自动适配")));Row(t,"背景策略",_background);Row(t,"轻量底板透明度",Stack(_opacity,Info("0（完全透明）～255（完全不透明）")));return t;}
    private void Initialize(){Combo(_sizing,Enum.GetValues<PreviewWindowSizingMode>().Select(UiStrings.PreviewSizeModeName).ToArray(),(int)_value.PreviewWindowSizingMode);_fixedW.Value=_value.FixedPreviewWidth;_fixedH.Value=_value.FixedPreviewHeight;var fonts=FontSettingsPolicy.Families();Combo(_uiMode,["产品默认","自定义字体"],(int)_value.UiFontMode);FontCombo(_uiFont,fonts,_value.UiFontFamily);_uiSize.Value=(decimal)_value.UiFontSize;Combo(_previewMode,["产品默认","跟随软件界面字体","自定义字体"],(int)_value.PreviewTextFontMode);FontCombo(_previewFont,fonts,_value.PreviewTextFontFamily);_previewSize.Value=(decimal)_value.PreviewTextFontSize;Combo(_overlayMode,["产品默认","自定义字体"],(int)_value.OverlayFontMode);FontCombo(_overlayFont,fonts,_value.OverlayFontFamily);_overlaySize.Value=(decimal)_value.OverlayFontSize;Combo(_background,Enum.GetValues<TranslationOverlayBackgroundStyle>().Select(UiStrings.BackgroundStyleName).ToArray(),(int)_value.OverlayBackgroundStyle);_opacity.Value=_value.OverlayBackgroundOpacity;_sizing.SelectedIndexChanged+=(_,_)=>UpdateEnabled();_uiMode.SelectedIndexChanged+=(_,_)=>UpdateEnabled();_previewMode.SelectedIndexChanged+=(_,_)=>UpdateEnabled();_overlayMode.SelectedIndexChanged+=(_,_)=>UpdateEnabled();_background.SelectedIndexChanged+=(_,_)=>UpdateEnabled();UpdateEnabled();}
    private void UpdateEnabled(){_uiFont.Enabled=_uiSize.Enabled=_uiMode.SelectedIndex==1;_previewFont.Enabled=_previewSize.Enabled=_previewMode.SelectedIndex==2;_overlayFont.Enabled=_overlaySize.Enabled=_overlayMode.SelectedIndex==1;_opacity.Enabled=_background.SelectedIndex==1;_fixedW.Enabled=_fixedH.Enabled=_sizing.SelectedIndex==2;}
    private void Commit(){_value.PreviewWindowSizingMode=(PreviewWindowSizingMode)_sizing.SelectedIndex;_value.FixedPreviewWidth=(int)_fixedW.Value;_value.FixedPreviewHeight=(int)_fixedH.Value;_value.UiFontMode=(UiFontMode)_uiMode.SelectedIndex;_value.UiFontFamily=_uiFont.Text;_value.UiFontSize=(float)_uiSize.Value;_value.PreviewTextFontMode=(PreviewTextFontMode)_previewMode.SelectedIndex;_value.PreviewTextFontFamily=_previewFont.Text;_value.PreviewTextFontSize=(float)_previewSize.Value;_value.OverlayFontMode=(OverlayFontMode)_overlayMode.SelectedIndex;_value.OverlayFontFamily=_overlayFont.Text;_value.OverlayFontSize=(float)_overlaySize.Value;_value.OverlayBackgroundStyle=(TranslationOverlayBackgroundStyle)_background.SelectedIndex;_value.OverlayBackgroundOpacity=(int)_opacity.Value;}
    private void ResetBaseline(){_sizing.SelectedIndex=0;_fixedW.Value=1220;_fixedH.Value=800;_uiMode.SelectedIndex=0;_uiFont.Text="";_uiSize.Value=10;_previewMode.SelectedIndex=0;_previewFont.Text="";_previewSize.Value=10;_overlayMode.SelectedIndex=0;_overlayFont.Text="";_overlaySize.Value=0;_background.SelectedIndex=0;_opacity.Value=105;UpdateEnabled();}
    private static TabPage Page(string name,Control c){var p=new TabPage(name);p.Controls.Add(c);return p;}private static TableLayoutPanel Table(){var t=new TableLayoutPanel{Dock=DockStyle.Fill,AutoScroll=true,ColumnCount=2,Padding=new Padding(16)};t.ColumnStyles.Add(new(SizeType.Absolute,210));t.ColumnStyles.Add(new(SizeType.Percent,100));return t;}private static NumericUpDown N(decimal min,decimal max)=>new(){Minimum=min,Maximum=max,Width=90};private static void Combo(ComboBox c,string[] items,int index){c.DropDownStyle=ComboBoxStyle.DropDownList;c.Items.AddRange(items);c.SelectedIndex=Math.Clamp(index,0,items.Length-1);c.Width=320;}private static void FontCombo(ComboBox c,string[] items,string value){c.DropDownStyle=ComboBoxStyle.DropDown;c.AutoCompleteMode=AutoCompleteMode.SuggestAppend;c.AutoCompleteSource=AutoCompleteSource.ListItems;c.Items.AddRange(items);c.Text=value??"";c.Width=300;FontDropDownPolicy.Apply(c,items,new ToolTip());}private static Label Info(string text)=>new(){Text=text,AutoSize=true,MaximumSize=new Size(470,0)};private static FlowLayoutPanel Stack(params Control[] c){var p=new FlowLayoutPanel{AutoSize=true,WrapContents=true};p.Controls.AddRange(c);return p;}private static void Row(TableLayoutPanel t,string label,Control c){var r=t.RowCount++;t.RowStyles.Add(new(SizeType.AutoSize));t.Controls.Add(new Label{Text=label,AutoSize=true,Margin=new Padding(3,9,3,3)},0,r);c.Dock=DockStyle.Top;c.Margin=new Padding(3,4,3,8);t.Controls.Add(c,1,r);}
}
