using System.Diagnostics;
using System.Runtime.InteropServices;
namespace ScreenshotTranslationUiTester;
internal sealed class GlobalMouseBindingHost:IDisposable
{
    internal bool IsHookInstalled=>_hook!=IntPtr.Zero;
    private const int WhMouseLl=14,LDown=0x201,RDown=0x204,MDown=0x207,XDown=0x20B,Wheel=0x20A;private readonly Func<InputBinding,bool> _protectedContext;private readonly Func<InputBinding,bool> _capture;private readonly Action<string> _trace;private readonly Dictionary<InputActionId,(InputBinding Binding,Action Trigger)> _bindings=[];private readonly HookProc _proc;private IntPtr _hook;
    internal GlobalMouseBindingHost(Func<InputBinding,bool> protectedContext,Func<InputBinding,bool> capture,Action<string> trace){_protectedContext=protectedContext;_capture=capture;_trace=trace;_proc=Hook;}
    internal void Apply(IEnumerable<(InputActionId Action,InputBinding Binding,Action Trigger)> values){_bindings.Clear();foreach(var value in values.Where(x=>x.Binding.Kind is InputBindingKind.MouseButton or InputBindingKind.MouseWheel))_bindings[value.Action]=(value.Binding,value.Trigger);EnsureHook();}
    internal InputBinding? RegisteredBinding(InputActionId action)=>_bindings.TryGetValue(action,out var entry)?entry.Binding:null;
    private void EnsureHook(){if(_hook!=IntPtr.Zero)return;using var process=Process.GetCurrentProcess();using var module=process.MainModule!;_hook=SetWindowsHookEx(WhMouseLl,_proc,GetModuleHandle(module.ModuleName),0);}
    private IntPtr Hook(int code,IntPtr wp,IntPtr lp){if(code<0)return CallNextHookEx(_hook,code,wp,lp);var message=wp.ToInt32();if(message is not (LDown or RDown or MDown or XDown or Wheel))return CallNextHookEx(_hook,code,wp,lp);var data=Marshal.PtrToStructure<MouseData>(lp);var mods=CurrentModifiers();var win=(GetAsyncKeyState(Keys.LWin)&0x8000)!=0||(GetAsyncKeyState(Keys.RWin)&0x8000)!=0;InputBinding binding=message switch{LDown=>new(InputBindingKind.MouseButton,MouseButton:InputMouseButton.Left,Ctrl:mods.HasFlag(Keys.Control),Alt:mods.HasFlag(Keys.Alt),Shift:mods.HasFlag(Keys.Shift),Win:win),RDown=>new(InputBindingKind.MouseButton,MouseButton:InputMouseButton.Right,Ctrl:mods.HasFlag(Keys.Control),Alt:mods.HasFlag(Keys.Alt),Shift:mods.HasFlag(Keys.Shift),Win:win),MDown=>new(InputBindingKind.MouseButton,MouseButton:InputMouseButton.Middle,Ctrl:mods.HasFlag(Keys.Control),Alt:mods.HasFlag(Keys.Alt),Shift:mods.HasFlag(Keys.Shift),Win:win),XDown=>new(InputBindingKind.MouseButton,MouseButton:(data.ButtonData>>16)==1?InputMouseButton.XButton1:InputMouseButton.XButton2,Ctrl:mods.HasFlag(Keys.Control),Alt:mods.HasFlag(Keys.Alt),Shift:mods.HasFlag(Keys.Shift),Win:win),_=>new(InputBindingKind.MouseWheel,Wheel:(short)(data.ButtonData>>16)>0?InputWheelDirection.Up:InputWheelDirection.Down,Ctrl:mods.HasFlag(Keys.Control),Alt:mods.HasFlag(Keys.Alt),Shift:mods.HasFlag(Keys.Shift),Win:win)};_trace($"Hook Msg=0x{message:X} Injected={(data.Flags&1)!=0} Modifiers={mods} Candidate={binding.DisplayName}");if(_capture(binding)){_trace("CaptureSessionOwnsInput=YES GlobalDispatch=SUPPRESSED UiMessage=SUPPRESSED");return new IntPtr(1);}if(_protectedContext(binding)){_trace("ContextProtected=YES Dispatch=PASS_THROUGH");return CallNextHookEx(_hook,code,wp,lp);}foreach(var (_,entry) in _bindings)if(entry.Binding==binding){_trace($"GlobalDispatch Action Binding={binding.DisplayName}");entry.Trigger();break;}return CallNextHookEx(_hook,code,wp,lp);}
    private static Keys CurrentModifiers(){var r=Keys.None;if((GetAsyncKeyState(Keys.ControlKey)&0x8000)!=0)r|=Keys.Control;if((GetAsyncKeyState(Keys.Menu)&0x8000)!=0)r|=Keys.Alt;if((GetAsyncKeyState(Keys.ShiftKey)&0x8000)!=0)r|=Keys.Shift;return r;}
    public void Dispose(){if(_hook!=IntPtr.Zero)UnhookWindowsHookEx(_hook);_hook=IntPtr.Zero;}
    private delegate IntPtr HookProc(int c,IntPtr w,IntPtr l);[StructLayout(LayoutKind.Sequential)]private struct MouseData{public Point Point;public uint ButtonData,Flags,Time;public IntPtr Extra;}
    [DllImport("user32.dll",SetLastError=true)]private static extern IntPtr SetWindowsHookEx(int id,HookProc proc,IntPtr module,uint thread);[DllImport("user32.dll")]private static extern bool UnhookWindowsHookEx(IntPtr hook);[DllImport("user32.dll")]private static extern IntPtr CallNextHookEx(IntPtr hook,int code,IntPtr wp,IntPtr lp);[DllImport("kernel32.dll",CharSet=CharSet.Auto)]private static extern IntPtr GetModuleHandle(string? name);[DllImport("user32.dll")]private static extern short GetAsyncKeyState(Keys key);
}
