using System.Text;
using System.Runtime.InteropServices;
namespace ScreenshotTranslationUiTester;
internal static class InputInteraction0505SelfTests
{
    internal static int Run(string output){Directory.CreateDirectory(output);var pass=0;var fail=0;var log=new StringBuilder();void Test(string name,Action body){try{body();pass++;log.AppendLine($"PASS {name}");}catch(Exception ex){fail++;log.AppendLine($"FAIL {name}: {ex.Message}");}}void True(bool value,string message){if(!value)throw new InvalidOperationException(message);}
        Test("keyboard format",()=>True(InputBindingDefaults.StartCapture.DisplayName.Contains("Ctrl")&&InputBindingDefaults.StartCapture.DisplayName.Contains("Z"),"format"));
        Test("mouse format",()=>True(InputBindingDefaults.ResetFit.DisplayName.Contains("Middle Mouse"),"mouse"));
        Test("wheel format",()=>True(InputBindingDefaults.ZoomIn.DisplayName.Contains("Wheel Up"),"wheel"));
        Test("keyboard match",()=>True(InputBindingMatcher.Keyboard(InputBindingDefaults.StartCapture,Keys.Z,Keys.Control|Keys.Alt),"keyboard match"));
        Test("wheel match",()=>True(InputBindingMatcher.Wheel(InputBindingDefaults.ZoomOut,-120,Keys.Control),"wheel match"));
        Test("mouse match",()=>True(InputBindingMatcher.Mouse(InputBindingDefaults.ResetFit,MouseButtons.Middle,Keys.None),"mouse match"));
        Test("same scope conflict",()=>True(InputBindingConflictDetector.Find([new(InputActionId.StartCapture,InputBindingScope.Global,InputBindingDefaults.StartCapture),new(InputActionId.ToggleResults,InputBindingScope.Global,InputBindingDefaults.StartCapture)]).Count==1,"conflict"));
        Test("cross scope conflict",()=>True(InputBindingConflictDetector.Find([new(InputActionId.StartCapture,InputBindingScope.Global,InputBindingDefaults.ZoomIn),new(InputActionId.PreviewZoomIn,InputBindingScope.PreviewLocal,InputBindingDefaults.ZoomIn)])[0].CrossScope,"cross"));
        Test("risky global wheel warning",()=>True(InputBindingFormatter.IsRiskyGlobal(new(InputBindingKind.MouseWheel,Wheel:InputWheelDirection.Up)),"warning"));
        Test("modified wheel safe warning",()=>True(!InputBindingFormatter.IsRiskyGlobal(InputBindingDefaults.ZoomIn),"false warning"));
        Test("empty binding",()=>True(new InputBinding().IsEmpty,"empty"));
        Test("configuration defaults",()=>{var s=new ApiSettings();ConfigurationManager.NormalizeAll(s);True(s.StartCaptureBinding==InputBindingDefaults.StartCapture&&s.PreviewResetFitBinding==InputBindingDefaults.ResetFit,"defaults");});
        Test("settings snapshot",()=>{var s=new ApiSettings{PreviewZoomInBinding=new(InputBindingKind.Keyboard,Keys.F6)};True(ApiSettingsSnapshot.Copy(s).PreviewZoomInBinding==s.PreviewZoomInBinding,"snapshot");});
        Test("zoom changes display state",()=>{using var b=new Bitmap(320,180);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());f.ZoomForSmoke(1.5f,new Point(10,10));True(!f.FitViewForSmoke&&f.ViewZoomForSmoke>1,"zoom");});
        Test("reset returns fit",()=>{using var b=new Bitmap(320,180);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());f.ZoomForSmoke(2,new Point());f.ResetFitForSmoke();True(f.FitViewForSmoke&&f.ViewZoomForSmoke==1,"fit");});
        Test("zoom clamps max",()=>{using var b=new Bitmap(20,20);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());f.ZoomForSmoke(100,new Point());True(f.ViewZoomForSmoke<=5,"max");});
        Test("zoom clamps min",()=>{using var b=new Bitmap(20,20);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());f.ZoomForSmoke(.001f,new Point());True(f.ViewZoomForSmoke>=.1f,"min");});
        Test("source clone exact size",()=>{using var b=new Bitmap(37,23);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());using var c=f.CloneSourceImageForTest();True(c.Size==b.Size,"source");});
        Test("translated absent",()=>{using var b=new Bitmap(37,23);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());True(f.CloneTranslatedImageForTest() is null,"absent");});
        Test("translated clone exact size",()=>{using var b=new Bitmap(37,23);using var t=new Bitmap(51,29);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());f.SetTranslatedDisplayForSmoke(t);using var c=f.CloneTranslatedImageForTest();True(c?.Size==t.Size,"translated");});
        Test("modifier is not primary",()=>True(!InputBindingMatcher.Keyboard(new(InputBindingKind.Keyboard,Keys.ControlKey,Ctrl:true),Keys.Z,Keys.Control),"modifier primary"));
        Test("continuous zoom twenty ticks",()=>{using var b=new Bitmap(1600,1200);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());var previous=0f;for(var i=0;i<20;i++){f.ZoomForSmoke(1.12f,new());True(f.ViewZoomForSmoke>=previous,"non continuous");previous=f.ViewZoomForSmoke;}for(var i=0;i<20;i++)f.ZoomForSmoke(1/1.12f,new());True(f.ViewZoomForSmoke<previous,"zoom out");});
        Test("reset clears pan and zoom",()=>{using var b=new Bitmap(1600,1200);using var f=new PreviewForm(b,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());f.ZoomForSmoke(2,new());f.ResetFitForSmoke();True(f.FitViewForSmoke&&f.PanOffsetForSmoke==Point.Empty,"reset");});
        Test("tray present while main visible",()=>{var path=Path.Combine(output,"tray-settings.json");using var main=new MainForm(path);main.Show();Application.DoEvents();True(main.Visible&&main.TrayIconPresentForSmoke,"tray absent");main.ExitForSmoke();});
        Test("tray remains through hide restore",()=>{var path=Path.Combine(output,"tray-cycle-settings.json");using var main=new MainForm(path);main.Show();Application.DoEvents();main.TrayHideForSmoke();True(main.TrayIconPresentForSmoke&&!main.Visible,"hidden tray");main.TrayRestoreForSmoke();True(main.TrayIconPresentForSmoke&&main.Visible,"restored tray");main.ExitForSmoke();});
        Test("capture cancel preserves committed",()=>{var path=Path.Combine(output,"transaction.json");using var main=new MainForm(path);main.Show();Application.DoEvents();var before=main.BindingDisplayForSmoke(InputActionId.StartCapture);main.BeginBindingCaptureForSmoke(InputActionId.StartCapture);True(main.ActiveBindingCaptureCountForSmoke==1,"not active");main.CancelBindingCaptureForSmoke();True(main.BindingDisplayForSmoke(InputActionId.StartCapture)==before,"changed");main.ExitForSmoke();});
        Test("only one capture session",()=>{var path=Path.Combine(output,"single.json");using var main=new MainForm(path);main.Show();Application.DoEvents();var first=main.BindingDisplayForSmoke(InputActionId.StartCapture);main.BeginBindingCaptureForSmoke(InputActionId.StartCapture);main.BeginBindingCaptureForSmoke(InputActionId.ToggleResults);True(main.ActiveBindingCaptureCountForSmoke==1&&main.BindingDisplayForSmoke(InputActionId.StartCapture)==first,"multiple capture");main.ExitForSmoke();});
        Test("tab switch cancels pending capture",()=>{var path=Path.Combine(output,"tab-cancel.json");using var main=new MainForm(path);main.Show();main.SelectSettingsTabForSmoke(1);Application.DoEvents();var before=main.BindingDisplayForSmoke(InputActionId.StartCapture);main.BeginBindingCaptureForSmoke(InputActionId.StartCapture);True(main.ActiveBindingCaptureCountForSmoke==1,"not capturing");main.SelectSettingsTabForSmoke(5);Application.DoEvents();True(main.ActiveBindingCaptureCountForSmoke==0&&main.BindingDisplayForSmoke(InputActionId.StartCapture)==before,"pending survived tab");main.ExitForSmoke();});
        Test("main page switch cancels pending capture",()=>{var path=Path.Combine(output,"page-cancel.json");using var main=new MainForm(path);main.Show();main.SelectSettingsTabForSmoke(1);Application.DoEvents();var before=main.BindingDisplayForSmoke(InputActionId.StartCapture);main.BeginBindingCaptureForSmoke(InputActionId.StartCapture);main.NavigateForSmoke("历史");Application.DoEvents();True(main.ActiveBindingCaptureCountForSmoke==0&&main.BindingDisplayForSmoke(InputActionId.StartCapture)==before,"pending survived page");main.ExitForSmoke();});
        Test("real modify does not own WinForms mouse capture",()=>{var path=Path.Combine(output,"no-local-capture.json");using var main=new MainForm(path);main.Show();main.SelectSettingsTabForSmoke(1);Application.DoEvents();True(main.ClickModifyForDiagnostic(InputActionId.StartCapture),"modify");Application.DoEvents();True(main.ActiveBindingCaptureCountForSmoke==1&&!main.ActiveBindingOwnsWinFormsMouseCaptureForSmoke,"capture editor still owns mouse");main.ExitForSmoke();});
        Test("real modify then tab event cancels",()=>{var path=Path.Combine(output,"real-tab-cancel.json");using var main=new MainForm(path);main.Show();main.SelectSettingsTabForSmoke(1);Application.DoEvents();var before=main.BindingDisplayForSmoke(InputActionId.StartCapture);True(main.ClickModifyForDiagnostic(InputActionId.StartCapture),"modify");Application.DoEvents();main.SelectSettingsTabForSmoke(5);Application.DoEvents();True(main.ActiveBindingCaptureCountForSmoke==0&&main.ActiveBindingActionForSmoke=="NONE"&&main.BindingDisplayForSmoke(InputActionId.StartCapture)==before,string.Join(" | ",main.BindingDiagnosticsForSmoke));main.ExitForSmoke();});
        Test("real modify A then modify B transfers one session",()=>{var path=Path.Combine(output,"real-modify-transfer.json");using var main=new MainForm(path);main.Show();main.SelectSettingsTabForSmoke(1);Application.DoEvents();True(main.ClickModifyForDiagnostic(InputActionId.StartCapture),"modify A");Application.DoEvents();True(main.ClickModifyForDiagnostic(InputActionId.ToggleResults),"modify B");Application.DoEvents();True(main.ActiveBindingCaptureCountForSmoke==1&&main.ActiveBindingActionForSmoke==InputActionId.ToggleResults.ToString(),string.Join(" | ",main.BindingDiagnosticsForSmoke));main.ExitForSmoke();});
        Test("escape global hotkey prioritizes binding rollback",()=>{var path=Path.Combine(output,"escape-priority.json");using var main=new MainForm(path);main.Show();main.SelectSettingsTabForSmoke(1);Application.DoEvents();var before=main.BindingDisplayForSmoke(InputActionId.StartCapture);True(main.ClickModifyForDiagnostic(InputActionId.StartCapture),"modify");Application.DoEvents();True(main.ActiveBindingCaptureCountForSmoke==1,"session absent");main.DispatchCancelBindingHotKeyForSmoke();Application.DoEvents();True(main.ActiveBindingCaptureCountForSmoke==0&&main.BindingDisplayForSmoke(InputActionId.StartCapture)==before&&main.BindingDiagnosticsForSmoke.Any(x=>x.Contains("EscapeHotKey Dispatch=CancelBindingCapture")),string.Join(" | ",main.BindingDiagnosticsForSmoke));main.ExitForSmoke();});
        Test("clear removes runtime keyboard registration",()=>{var path=Path.Combine(output,"runtime-clear.json");using var main=new MainForm(path);main.Show();Application.DoEvents();var custom=new InputBinding(InputBindingKind.Keyboard,Keys.F9);main.ApplyBindingForSmoke(InputActionId.StartCapture,custom);True(main.RuntimeBindingForSmoke(InputActionId.StartCapture)==custom.DisplayName,"custom runtime absent");main.ApplyBindingForSmoke(InputActionId.StartCapture,new());True(main.BindingDisplayForSmoke(InputActionId.StartCapture).Contains("未绑定")&&main.RuntimeBindingForSmoke(InputActionId.StartCapture)=="NONE","old F9 runtime survived clear");main.ExitForSmoke();});
        Test("restore default replaces runtime keyboard registration",()=>{var path=Path.Combine(output,"runtime-default.json");using var main=new MainForm(path);main.Show();Application.DoEvents();var custom=new InputBinding(InputBindingKind.Keyboard,Keys.F9);main.ApplyBindingForSmoke(InputActionId.StartCapture,custom);main.ApplyBindingForSmoke(InputActionId.StartCapture,InputBindingDefaults.StartCapture);True(main.RuntimeBindingForSmoke(InputActionId.StartCapture)==InputBindingDefaults.StartCapture.DisplayName&&main.RuntimeBindingForSmoke(InputActionId.StartCapture)!=custom.DisplayName,"runtime not replaced");main.ExitForSmoke();});
        Test("clear removes runtime mouse dispatch",()=>{var path=Path.Combine(output,"runtime-mouse-clear.json");using var main=new MainForm(path);main.Show();Application.DoEvents();var custom=new InputBinding(InputBindingKind.MouseButton,MouseButton:InputMouseButton.XButton1);main.ApplyBindingForSmoke(InputActionId.StartCapture,custom);True(main.RuntimeBindingForSmoke(InputActionId.StartCapture)==custom.DisplayName,"mouse runtime absent");main.ApplyBindingForSmoke(InputActionId.StartCapture,new());True(main.RuntimeBindingForSmoke(InputActionId.StartCapture)=="NONE","old mouse runtime survived clear");main.ExitForSmoke();});
        Test("restore keyboard default removes runtime mouse dispatch",()=>{var path=Path.Combine(output,"runtime-mouse-default.json");using var main=new MainForm(path);main.Show();Application.DoEvents();var custom=new InputBinding(InputBindingKind.MouseButton,MouseButton:InputMouseButton.XButton1);main.ApplyBindingForSmoke(InputActionId.StartCapture,custom);main.ApplyBindingForSmoke(InputActionId.StartCapture,InputBindingDefaults.StartCapture);True(main.RuntimeBindingForSmoke(InputActionId.StartCapture)==InputBindingDefaults.StartCapture.DisplayName&&main.RuntimeBindingForSmoke(InputActionId.StartCapture)!=custom.DisplayName,"mouse dispatch survived restore");main.ExitForSmoke();});
        Test("SendInput physical chain middle",()=>{var path=Path.Combine(output,"sendinput-middle.json");using var main=new MainForm(path);main.Show();main.SelectSettingsTabForSmoke(1);Application.DoEvents();True(main.ClickModifyForDiagnostic(InputActionId.StartCapture),"modify");Application.DoEvents();SendMouse(0x20);for(var i=0;i<20;i++){Application.DoEvents();Thread.Sleep(5);}True(main.BindingDisplayForSmoke(InputActionId.StartCapture).Contains("Middle Mouse"),string.Join(" | ",main.BindingDiagnosticsForSmoke));True(main.BindingDiagnosticsForSmoke.Any(x=>x.Contains("HookCapture"))&&main.BindingDiagnosticsForSmoke.Any(x=>x.Contains("Commit Binding")),"chain missing");main.ExitForSmoke();});
        File.WriteAllText(Path.Combine(output,"results.txt"),log+ $"TOTAL {pass+fail} PASS {pass} FAIL {fail}\n");return fail==0?0:1;
    }
    [DllImport("user32.dll")]private static extern bool PostMessage(IntPtr handle,int message,IntPtr wParam,IntPtr lParam);
    private static void SendMouse(uint flags,uint data=0){var input=new INPUT{Type=0,Mouse=new MOUSEINPUT{Flags=flags,MouseData=data}};if(SendInput(1,[input],Marshal.SizeOf<INPUT>())!=1)throw new InvalidOperationException($"SendInput failed error={Marshal.GetLastWin32Error()} size={Marshal.SizeOf<INPUT>()}");}
    [StructLayout(LayoutKind.Explicit)]private struct INPUT{[FieldOffset(0)]public uint Type;[FieldOffset(8)]public MOUSEINPUT Mouse;}
    [StructLayout(LayoutKind.Sequential)]private struct MOUSEINPUT{public int X,Y;public uint MouseData,Flags,Time;public IntPtr Extra;}
    [DllImport("user32.dll",SetLastError=true)]private static extern uint SendInput(uint count,INPUT[] inputs,int size);
}
