namespace ScreenshotTranslationUiTester;
internal static class ManualAcceptanceRepair3SelfTests
{
    internal static int Run(string output)
    {
        Directory.CreateDirectory(output);var lines=new List<string>();var pass=0;var fail=0;
        void Test(string name,Action action){try{action();lines.Add("PASS "+name);pass++;}catch(Exception ex){lines.Add("FAIL "+name+": "+ex.Message);fail++;}}
        static void Need(bool value,string message){if(!value)throw new InvalidOperationException(message);}
        Test("Single instance mutex and activation signal",()=>{using var first=new SingleInstanceCoordinator();Need(first.IsPrimary,"first");using var signal=new ManualResetEventSlim();first.Start(()=>signal.Set());using var second=new SingleInstanceCoordinator();Need(!second.IsPrimary,"second primary");Need(second.NotifyPrimary(),"notify");Need(signal.Wait(3000),"activation");using var third=new SingleInstanceCoordinator();Need(!third.IsPrimary,"third primary");});
        var config=Path.Combine(output,"settings.json");ConfigurationManager.Save(config,new ApiSettings{PreviewChromeMode=PreviewChromeMode.GameCompact,PreviewDefaultText=PreviewDefaultText.Organized,PreviewTextPanelVisible=true,VisualModel=VisualModelKind.Off});
        Test("Text mode separate from persistent visibility",()=>{using var image=new Bitmap(640,360);using(var preview=new PreviewForm(image,PreviewMode.OcrOnly,ConfigurationManager.Load(config,false),new OcrService(),new TranslationService())){preview.Show();Need(preview.TextModeItemsForSmoke.SequenceEqual(new[]{"OCR 原文","整理后原文","译文"}),string.Join('|',preview.TextModeItemsForSmoke));preview.SetTextViewForSmoke(TextViewMode.Organized);preview.ToggleTextPanelForSmoke();Need(preview.TextViewForSmoke==TextViewMode.Organized&&!preview.TextPanelVisibleSettingForSmoke&&preview.TextPanelCollapsedForSmoke,"hide");var saved=ConfigurationManager.Load(config,false);saved.PreviewTextPanelVisible=false;ConfigurationManager.Save(config,saved);}var restart=ConfigurationManager.Load(config,false);Need(!restart.PreviewTextPanelVisible&&restart.PreviewDefaultText==PreviewDefaultText.Organized,"restart hidden");using var preview2=new PreviewForm(image,PreviewMode.OcrOnly,restart,new OcrService(),new TranslationService());preview2.Show();Need(preview2.TextPanelCollapsedForSmoke,"new preview");preview2.ToggleTextPanelForSmoke();Need(preview2.TextPanelVisibleSettingForSmoke&&preview2.TextViewForSmoke==TextViewMode.Organized,"show processed");});
        Test("Settings and open Preview synchronize both directions",()=>{using var main=new MainForm(config);main.Show();Application.DoEvents();using var image=new Bitmap(320,180);var preview=main.OpenPreviewForSmoke(image);main.SetPreviewTextPanelVisibleForSmoke(false);Application.DoEvents();Need(preview.TextPanelCollapsedForSmoke&&!main.PreviewTextPanelVisibleForSmoke,"settings hide");preview.ToggleTextPanelForSmoke();Application.DoEvents();Need(main.PreviewTextPanelVisibleForSmoke&&!preview.TextPanelCollapsedForSmoke,"preview to settings");main.ExitForSmoke();});
        Test("Settings content border screenshots Day Night",()=>{using var main=new MainForm(config);main.Show();main.NavigateForSmoke("设置");foreach(var pair in new[]{(ApplicationThemeMode.Night,"night"),(ApplicationThemeMode.Day,"day")}){main.SetThemeForSmoke(pair.Item1);Application.DoEvents();using var shot=new Bitmap(main.ClientSize.Width,main.ClientSize.Height);main.DrawCurrentPageForSmoke(shot);shot.Save(Path.Combine(output,$"settings-border-{pair.Item2}.png"));}main.ExitForSmoke();});
        lines.Add($"TOTAL={pass+fail} PASS={pass} FAIL={fail}");lines.Add("RealApiCalls=0");lines.Add("ActiveOperations=0");lines.Add("Worker residue=NONE");File.WriteAllLines(Path.Combine(output,"0503-repair-tests.txt"),lines);return fail==0?0:1;
    }
}
