namespace ScreenshotTranslationUiTester;
internal static class ManualAcceptanceRepair2SelfTests
{
    internal static int Run(string output)
    {
        Directory.CreateDirectory(output);var lines=new List<string>();var pass=0;var fail=0;
        void Test(string name,Action action){try{action();lines.Add("PASS "+name);pass++;}catch(Exception ex){lines.Add("FAIL "+name+": "+ex.Message);fail++;}}
        static void Require(bool value,string message){if(!value)throw new InvalidOperationException(message);}
        var config=Path.Combine(output,"settings.json");ConfigurationManager.Save(config,new ApiSettings{CloseMainWindowBehavior=CloseMainWindowBehavior.MinimizeToTray,PreviewChromeMode=PreviewChromeMode.GameCompact,VisualModel=VisualModelKind.Off,HotKeyModifiers="Ctrl + Shift",HotKeyKey="F11"});
        Test("Tray hotkey application lifetime hide restore 30",()=>{using var main=new MainForm(config);main.Show();for(var spin=0;spin<50&&!main.HotKeyLifetimeValidForSmoke;spin++){Application.DoEvents();Thread.Sleep(10);}Require(main.HotKeyLifetimeValidForSmoke,"startup");for(var i=0;i<30;i++){main.TrayHideForSmoke();Application.DoEvents();Require(main.HotKeyLifetimeValidForSmoke,$"hide {i}");main.TrayRestoreForSmoke();Application.DoEvents();Require(main.HotKeyLifetimeValidForSmoke,$"restore {i}");}main.ExitForSmoke();});
        Test("Simple Preview exposes OCR Translation Hidden and collapses 30",()=>{using var image=new Bitmap(640,360);using var preview=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{PreviewChromeMode=PreviewChromeMode.GameCompact,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());preview.Show();Application.DoEvents();Require(preview.TextModeItemsForSmoke.SequenceEqual(new[]{"OCR 原文","译文","隐藏"}),string.Join('|',preview.TextModeItemsForSmoke));for(var i=0;i<30;i++){preview.SetTextViewForSmoke(TextViewMode.Translation);Require(!preview.TextPanelCollapsedForSmoke,"translation");preview.SetTextViewForSmoke(TextViewMode.Hidden);Require(preview.TextPanelCollapsedForSmoke,"hidden");preview.SetTextViewForSmoke(TextViewMode.RawOcr);Require(!preview.TextPanelCollapsedForSmoke,"ocr");preview.SetTextViewForSmoke(TextViewMode.Hidden);Require(preview.TextPanelCollapsedForSmoke,"hidden2");}preview.Close();});
        Test("History random resize 200 keeps items and thumbnail instances",()=>{using var main=new MainForm(config);main.Show();Application.DoEvents();main.NavigateForSmoke("历史");main.SeedHistoryForSmoke(20);var state=main.HistoryStateForSmoke();var decodes=main.HistoryThumbnailDecodeCountForSmoke;var random=new Random(502);for(var i=0;i<200;i++){main.ResizeHistoryForSmoke(random.Next(920,1950));Application.DoEvents();}Require(main.HistoryStateForSmoke()==state,"state changed");Require(main.HistoryThumbnailDecodeCountForSmoke==decodes,$"decode {decodes}->{main.HistoryThumbnailDecodeCountForSmoke}");Require(main.HistoryBlankClicksForSmoke(100)==100,"blank points");Require(main.HistoryStateForSmoke()==state,"blank state");main.ExitForSmoke();});
        Test("Theme border scrollbar Day Night Day 20",()=>{using var main=new MainForm(config);main.Show();Application.DoEvents();var bounds=main.SettingsTabBoundsForSmoke();for(var i=0;i<20;i++){Require(main.HistoryScrollThemeForSmoke(ApplicationThemeMode.Day),"day");Require(main.SettingsUsesThemedBorderForSmoke(),"day border");Require(main.HistoryScrollThemeForSmoke(ApplicationThemeMode.Night),"night");Require(main.SettingsUsesThemedBorderForSmoke(),"night border");Require(main.HistoryScrollThemeForSmoke(ApplicationThemeMode.Day),"day2");Require(main.SettingsTabBoundsForSmoke()==bounds,"tab layout changed");}main.ExitForSmoke();});
        lines.Add($"TOTAL={pass+fail} PASS={pass} FAIL={fail}");lines.Add("RealApiCalls=0");lines.Add("ActiveOperations=0");lines.Add("Worker residue=NONE");File.WriteAllLines(Path.Combine(output,"0502-repair-tests.txt"),lines);return fail==0?0:1;
    }
}
