namespace ScreenshotTranslationUiTester;

internal static class ProductizationSelfTests
{
    internal static int Run(string output)
    {
        Directory.CreateDirectory(output);var lines=new List<string>();var failed=0;
        void Test(string name,Action action){try{action();lines.Add($"PASS {name}");}catch(Exception ex){failed++;lines.Add($"FAIL {name}: {ex.Message}");}}
        var config=Path.Combine(output,"settings.json");
        Test("Settings schema 10",()=>{ConfigurationManager.Save(config,new ApiSettings());var value=ConfigurationManager.Load(config,false);Require(value.SettingsSchemaVersion==10,"schema");});
        Test("Three resident pages / 1000 switches",()=>{using var main=new MainForm(config);PrepareHidden(main);main.Show();for(var i=0;i<1000;i++)Require(main.NavigateWithoutEventsForSmoke(MainForm.MainPageNamesForSmoke[i%3]),$"switch {i}");Require(main.MainHostControlCountForSmoke==3,"host count");main.Hide();});
        Test("Theme changes colors only",()=>{using var main=new MainForm(config);PrepareHidden(main);main.Show();Require(main.ThemePreservesBoundsForSmoke(),"bounds changed");main.Hide();});
        Test("Tray restore 50 cycles keeps pages and hotkey",()=>{using var main=new MainForm(config);PrepareHidden(main);main.Show();Require(main.TrayRestoreCyclesForSmoke(50),"tray cycle invariant");main.Hide();});
        Test("Preview hidden text releases panel",()=>{using var image=new Bitmap(640,360);using var preview=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off,PreviewDefaultText=PreviewDefaultText.Hidden},new OcrService(),new TranslationService());Require(preview.TextPanelCollapsedForSmoke,"panel remains visible");Require(!preview.PlacementTimerExistsForSmoke,"placement timer");});
        Test("Preview topmost remembered input",()=>{using var image=new Bitmap(640,360);using var preview=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off,PreviewAlwaysOnTop=true},new OcrService(),new TranslationService());Require(preview.TopMost,"not topmost");});
        Test("Persistent history survives new service",()=>{var root=Fresh(Path.Combine(output,"history-persist"));using(var first=new SessionServices(root)){using var image=new Bitmap(320,180);first.AddHistory(image,OcrEngineKind.Rapid,"source","translation","zh",new ApiSettings{HistoryLimit=20});Require(first.HistoryCount==1,"first count");}using var second=new SessionServices(root);Require(second.HistoryCount==1,"restart count");});
        Test("History 20 restart and five previews",()=>{var root=Fresh(Path.Combine(output,"history-20"));using(var first=new SessionServices(root)){for(var i=0;i<20;i++){using var image=new Bitmap(320+i,180);using(var g=Graphics.FromImage(image)){g.Clear(Color.FromArgb((i*31)%255,(i*53)%255,(i*79)%255));g.DrawString($"history-{i}",SystemFonts.DefaultFont,Brushes.White,8,8);}first.AddHistory(image,OcrEngineKind.Rapid,$"source-{i}",$"translation-{i}","zh",new ApiSettings{HistoryLimit=20});}Require(first.HistoryCount==20,"initial 20");}using var second=new SessionServices(root);Require(second.HistoryCount==20,"restart 20");foreach(var item in second.SnapshotHistory().Where((_,i)=>i%4==0).Take(5)){using var stream=new MemoryStream(item.OriginalPng);using var source=new Bitmap(stream);using var image=new Bitmap(source);using var preview=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());Require(preview.ClientSize.Width>0&&image.Width>=320,"preview restore");}});
        Test("History count cleanup",()=>{var root=Fresh(Path.Combine(output,"history-count"));using var service=new SessionServices(root);for(var i=0;i<4;i++){using var image=new Bitmap(80,60);service.AddHistory(image,OcrEngineKind.Rapid,$"s{i}",$"t{i}","zh",new ApiSettings{HistoryLimit=2,HistoryCleanupByCount=true,HistoryCleanupByAge=false,HistoryCleanupBySpace=false});}Require(service.HistoryCount==2,"count policy");});
        Test("History age cleanup keeps cache separate",()=>{var parent=Fresh(Path.Combine(output,"history-age-parent"));var root=Path.Combine(parent,"history");var cache=Path.Combine(parent,"translation-cache.sentinel");File.WriteAllText(cache,"keep");using(var service=new SessionServices(root)){using var image=new Bitmap(80,60);service.AddHistory(image,OcrEngineKind.Rapid,"old","old","zh",new ApiSettings{HistoryCleanupByCount=false,HistoryCleanupByAge=false,HistoryCleanupBySpace=false});}var index=Path.Combine(root,"index.json");var array=System.Text.Json.Nodes.JsonNode.Parse(File.ReadAllText(index))!.AsArray();foreach(var node in array)node!["Timestamp"]=DateTimeOffset.Now.AddDays(-10);File.WriteAllText(index,array.ToJsonString());using(var service=new SessionServices(root)){service.ApplyHistoryCleanup(new ApiSettings{HistoryCleanupByCount=false,HistoryCleanupByAge=true,HistoryRetentionDays=1,HistoryCleanupBySpace=false});Require(service.HistoryCount==0,"age policy");}Require(File.Exists(cache)&&File.ReadAllText(cache)=="keep","cache touched");});
        Test("History space cleanup",()=>{var root=Fresh(Path.Combine(output,"history-space"));using var service=new SessionServices(root);using var image=new Bitmap(1800,1200);using(var g=Graphics.FromImage(image)){g.Clear(Color.Black);for(var i=0;i<1000;i++)g.FillRectangle(new SolidBrush(Color.FromArgb((i*31)%255,(i*47)%255,(i*71)%255)),i%1800,(i*13)%1200,20,20);}service.AddHistory(image,OcrEngineKind.Rapid,"s","t","zh",new ApiSettings{HistoryCleanupByCount=false,HistoryCleanupByAge=false,HistoryCleanupBySpace=true,HistoryMaximumMegabytes=32});Require(service.HistoryUsageBytes<=32L*1024*1024,"space policy");});
        Test("Model manager detects missing and repairs quarantine",()=>{var root=Fresh(Path.Combine(output,"model-manager"));var component=Path.Combine(root,"PP-DocLayout-S");Directory.CreateDirectory(component);File.WriteAllText(Path.Combine(component,"model.pdmodel"),"fixture");Require(ModelManagerOperations.IsInstalled(component),"installed not detected");Require(ModelManagerOperations.MoveToQuarantine(component),"delete/quarantine");Require(!ModelManagerOperations.IsInstalled(component)&&ModelManagerOperations.IsInstalled(ModelManagerOperations.QuarantinePath(component)),"missing not detected");Require(ModelManagerOperations.RestoreFromQuarantine(component),"repair");Require(File.Exists(Path.Combine(component,"model.pdmodel")),"repair content");});
        Test("Required Rapid runtime ready with PP-S optional off",()=>{var ocr=new OcrRuntimeManager(AppContext.BaseDirectory,new OcrService());try{var rapid=ocr.GetStatus(OcrEngineKind.Rapid);var rapidProbe=Task.Run(()=>ocr.CheckAsync(OcrEngineKind.Rapid,CancellationToken.None)).GetAwaiter().GetResult();var python=ModelManagerOperations.ResolveRapidPython(AppContext.BaseDirectory);Require(rapid.Ready,"Rapid missing");Require(rapidProbe.Ready,"Rapid worker probe failed");Require(File.Exists(python),"bundled Python missing");Require(ModelManagerOperations.RequiredStartupComponentsReady(true,true),"ready policy rejected required components");Require(!ModelManagerOperations.RequiredStartupComponentsReady(true,false),"hotkey failure ignored");}finally{Task.Run(async()=>await ocr.DisposeAsync()).GetAwaiter().GetResult();}});
        File.WriteAllLines(Path.Combine(output,"productization-self-tests.txt"),lines.Append($"TOTAL={lines.Count} PASS={lines.Count-failed} FAIL={failed}").Append("RealApiCalls=0").Append("ActiveOperations=0"));return failed==0?0:2;
    }
    private static void PrepareHidden(Form form){form.ShowInTaskbar=false;form.Opacity=0;form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-32000,-32000);}
    private static void Require(bool value,string message){if(!value)throw new InvalidOperationException(message);}
    private static string Fresh(string path){if(Directory.Exists(path))Directory.Delete(path,true);Directory.CreateDirectory(path);return path;}
}
