using System.Diagnostics;
using System.Text;
using System.Text.Json;

namespace ScreenshotTranslationUiTester;

internal static class Repair065SelfTests
{
    internal static int Run(string output)
    {
        Directory.CreateDirectory(output);var pass=0;var fail=0;var rows=new List<string>();
        void T(string name,Action test){try{test();pass++;rows.Add("PASS | "+name);}catch(Exception ex){fail++;rows.Add("FAIL | "+name+" | "+ex.Message);}}
        static void A(bool value,string message){if(!value)throw new InvalidOperationException(message);}
        T("Render Coverage summary",()=>{var r=R("C",RegionRoleType.BodyParagraph,new(10,10,120,50),"译文");using var b=Canvas(200,100);using var rr=RegionRendererV2.Render(b,[r],new());var s=RenderCoverageAudit.Build("fixture",[r],rr.Diagnostics??[]);A(s.TranslationAvailableRegionCount==1&&s.CommittedRegionCount==1&&s.PerRole.Count==1,"coverage totals wrong");});
        T("UnexpectedSkip fails validation",()=>{var r=R("U",RegionRoleType.BodyParagraph,new(1,1,20,10),"有效译文");var d=new RegionRenderDiagnostic("U",r.RoleType,1,r.TranslationText.Length,RegionRenderStatus.PreservedOriginal,0,0,0,0,0,0,"No fit",[],[],DecisionStage:"Layout",DecisionCode:"NoSafeLayout",TranslationUnitId:r.TranslationUnitId);var s=RenderCoverageAudit.Build("fixture",[r],[d]);A(s.UnexpectedSkipCount==1&&!RenderCoverageAudit.PassesProductCoverage(s),"unexpected skip passed");});
        T("Per-role coverage",()=>{var rs=new[]{R("T",RegionRoleType.Title,new(5,5,100,30),"标题"),R("B",RegionRoleType.BodyParagraph,new(5,50,100,40),"正文")};using var b=Canvas(160,120);using var x=RegionRendererV2.Render(b,rs,new());var s=RenderCoverageAudit.Build("roles",rs,x.Diagnostics??[]);A(s.PerRole.Select(v=>v.Role).ToHashSet().SetEquals(["Title","BodyParagraph"]),"role rows missing");});
        T("Title anchor drift",()=>{using var b=Canvas(520,160);var r=R("T",RegionRoleType.Title,new(35,22,220,38),"这是一个安全标题译文");using var x=RegionRendererV2.Render(b,[r],new());var d=x.Diagnostics!.Single();A(d.AtomicRegionCommitted&&d.AnchorDeltaX>=-2&&d.AnchorDeltaX<=12,$"anchor drift {d.AnchorDeltaX}");});
        T("Asymmetric Title SafeExpand",()=>{using var b=Canvas(600,180);var r=R("T",RegionRoleType.Title,new(40,20,140,34),"需要更多水平空间的安全中文标题");using var x=RegionRendererV2.Render(b,[r],new RenderSettings{SafeExpansionScale=1.8f});var d=x.Diagnostics!.Single();A(d.ExpansionDirection is "RightDown" or "None"&&d.RenderTextStartX>=38,"title expanded left");});
        T("Real Title runtime admission",()=>{var r=R("RT",RegionRoleType.Title,new(20,18,260,45),"真实映射标题");var doc=new RecognitionDocumentV2();doc.Regions.Add(r);doc.TranslationUnits.Add(new("TU-RT",["RT"],RegionRoleType.Title,"SOURCE",0,false));TranslationMappingV2.Apply(doc,new Dictionary<string,string>{{"TU-RT","真实映射标题"}},0);using var b=Canvas(400,120);using var x=RegionRendererV2.Render(b,doc.Regions,new());A(x.Diagnostics!.Single().AtomicRegionCommitted,"mapped runtime title skipped");});
        T("April Long shared body scale",()=>{var rs=LongBody();var c=TypographyContextPlanner.Plan(rs,new());A(c.LongForm&&c.BaseBodyFontSize<=22&&c.AllowedMinFontSize<c.AllowedMaxFontSize,"invalid context band");});
        T("Base font size robust estimation",()=>{var rs=LongBody();rs[0].SourceLinePolygons=[GeometryV2.RectanglePolygon(new(10,10,500,80))];var c=TypographyContextPlanner.Plan(rs,new());A(c.BaseBodyFontSize<=22,"outlier inflated base");});
        T("Bold/Italic no size drift",()=>{using var b=Canvas(700,1000);var rs=LongBody();using var x=RegionRendererV2.Render(b,rs,new());var sizes=x.Diagnostics!.Where(d=>d.AtomicRegionCommitted).Select(d=>d.FontSize).ToArray();A(sizes.Length>=2&&sizes.Max()-sizes.Min()<=3,"style caused size tier drift");});
        T("Body fit fallback before PreserveOriginal",()=>{using var b=Canvas(700,1000);var rs=LongBody();rs[1].TranslationText=new string('译',80);using var x=RegionRendererV2.Render(b,rs,new());var d=x.Diagnostics!.Single(v=>v.RegionId==rs[1].RegionId);A(d.FontSize==0||d.FontSize>=TypographyContextPlanner.Plan(rs,new()).AllowedMinFontSize,"escaped allowed band");});
        T("TranslationAvailable no-commit audit",()=>{var r=R("A",RegionRoleType.BodyParagraph,new(1,1,20,10),"译文");var s=RenderCoverageAudit.Build("audit",[r],[]);A(s.UnexpectedSkipCount==1&&s.Regions.Single().TranslatedText=="译文","missing decision not audited");});
        T("Faranna 0.5.0.6.4 regression detection",()=>{using var b=Canvas(360,150,Color.FromArgb(105,164,169));var r=R("F",RegionRoleType.BodyParagraph,new(30,30,260,60),"法兰妮正文");var p=BackgroundIntegrationPlanner.Plan(b,r,r.BoundingBox,[r]);using var roi=BackgroundIntegrationExecutor.ExecuteRoi(b,p,Rectangle.Inflate(p.CleanupBounds,4,4));A(roi.Committed&&roi.Bounds.Width<350,"giant flat patch path returned");});
        T("Panel geometry differs from uncertain text mask",()=>{using var b=Canvas(300,120,Color.FromArgb(100,160,165));var r=R("P",RegionRoleType.BodyParagraph,new(30,25,200,45),"连续面板");var p=BackgroundIntegrationPlanner.Plan(b,r,r.BoundingBox,[r]);var ink=0;for(var y=p.CleanupBounds.Top;y<p.CleanupBounds.Bottom;y++)for(var x=p.CleanupBounds.Left;x<p.CleanupBounds.Right;x++)if(p.CleanupMask[x,y])ink++;A(p.BackgroundType==BackgroundSurfaceType.FlatColor&&ink==p.CleanupBounds.Width*p.CleanupBounds.Height,"reliable panel was not admitted as panel geometry");});
        T("No giant Faranna patch",()=>{using var b=Canvas(500,240,Color.FromArgb(105,164,169));var r=R("F",RegionRoleType.BodyParagraph,new(80,70,250,60),"连续正文");using var x=RegionRendererV2.Render(b,[r],new());A(x.CopyMetrics!.TemporaryBitmapBytes<(long)b.Width*b.Height*4*2,"full panel-sized temporary patch");});
        T("Per-region full bitmap clone forbidden",()=>{using var b=Canvas(900,1400);var rs=Enumerable.Range(0,10).Select(i=>R("R"+i,RegionRoleType.BodyParagraph,new(40,30+i*120,600,80),"测试译文")).ToArray();using var x=RegionRendererV2.Render(b,rs,new());A(x.CopyMetrics!.FullBitmapCloneCount==1&&x.CopyMetrics.FullBitmapBlitCount==0,"per-region full copy remains");});
        T("ROI atomic rollback",()=>{using var b=Canvas(400,200);var r=R("R",RegionRoleType.BodyParagraph,new(80,50,160,55),"局部事务");using var x=RegionRendererV2.Render(b,[r],new());A(x.Diagnostics!.Single().AtomicRegionCommitted&&x.CopyMetrics!.RegionBitmapAllocationCount>0,"ROI commit failed");});
        T("Long image bitmap-copy performance",()=>{using var b=Canvas(1000,1800);var rs=Enumerable.Range(0,12).Select(i=>R("L"+i,i%3==0?RegionRoleType.Dialogue:RegionRoleType.BodyParagraph,new(80,40+i*135,700,90),new string('译',30))).ToArray();var sw=Stopwatch.StartNew();using var x=RegionRendererV2.Render(b,rs,new());sw.Stop();A(x.CopyMetrics!.FullBitmapCloneCount==1&&x.CopyMetrics.TotalPixelBytesCopied<(long)b.Width*b.Height*4*5,"copy volume too high");File.WriteAllText(Path.Combine(output,"RENDER-PERFORMANCE.json"),JsonSerializer.Serialize(new{rendererMs=sw.ElapsedMilliseconds,x.CopyMetrics},new JsonSerializerOptions{WriteIndented=true}));});
        T("Font dropdown real width calculation",()=>{using var c=new ComboBox{Width=120};var names=new[]{"Microsoft YaHei UI","Bahnschrift SemiLight","Segoe UI Variable Text"};FontDropDownPolicy.Apply(c,names,new ToolTip());A(c.DropDownWidth>=names.Max(n=>TextRenderer.MeasureText(n,c.Font,Size.Empty,TextFormatFlags.NoPadding|TextFormatFlags.SingleLine).Width)+SystemInformation.VerticalScrollBarWidth,"font name clipped");});
        T("Runtime build identity",()=>A(BuildIdentity.ProductVersion=="0.5.0.6.5"&&BuildIdentity.BuildId.Contains("0.5.0.6.5"),"stale identity"));
        T("Quantity x1/x6 unchanged",()=>{foreach(var q in new[]{"x1","x6","I have 3 friends."}){var r=R("Q",RegionRoleType.UILabel,new(1,1,100,30),q);A(r.TranslationText==q&&!TranslationAuthorizationPolicy.ShouldPreserve(r,q),"quantity behavior changed: "+q);}});
        File.WriteAllLines(Path.Combine(output,"REPAIR-065-SELFTESTS.txt"),rows,Encoding.UTF8);File.WriteAllText(Path.Combine(output,"SUMMARY.txt"),$"PASS={pass}\nFAIL={fail}\nRealApiCalls=0\nActiveOperations=0\nWorkerResidue=NONE",Encoding.UTF8);return fail==0?0:1;
    }
    private static List<RecognitionRegion> LongBody()=>new[]{("B",RegionRoleType.BodyParagraph), ("D",RegionRoleType.Dialogue),("N",RegionRoleType.Narration),("B2",RegionRoleType.BodyParagraph)}.Select((x,i)=>R(x.Item1,x.Item2,new(40,40+i*220,560,170),new string('译',38))).ToList();
    private static Bitmap Canvas(int w,int h,Color? color=null){var b=new Bitmap(w,h);using var g=Graphics.FromImage(b);g.Clear(color??Color.FromArgb(35,20,80));return b;}
    private static RecognitionRegion R(string id,RegionRoleType role,RectangleF box,string text)=>new(){RegionId=id,TranslationUnitId="TU-"+id,RoleType=role,Polygon=GeometryV2.RectanglePolygon(box),SourceLinePolygons=[GeometryV2.RectanglePolygon(box)],SourceBlockIds=[id],OcrText="SOURCE",StructuredText="SOURCE",TranslationText=text,CoverageValid=true};
}
