using System.Text;

namespace ScreenshotTranslationUiTester;

internal static class Repair063SelfTests
{
    internal static int Run(string output)
    {
        Directory.CreateDirectory(output);var pass=0;var fail=0;var log=new StringBuilder();
        void T(string name,Action action){try{action();pass++;log.AppendLine("PASS "+name);}catch(Exception ex){fail++;log.AppendLine($"FAIL {name}: {ex}");}}
        static void A(bool value,string message){if(!value)throw new InvalidOperationException(message);}
        T("Preserved unit is not required from API mapping",()=>{var d=new RecognitionDocumentV2{TranslationGeneration=1};var a=R("A","GRP001",false);var b=R("B","GRP002",true);d.Regions.AddRange([a,b]);d.TranslationUnits.Add(new("GRP001",["A"],RegionRoleType.BodyParagraph,"source",1,false));d.TranslationUnits.Add(new("GRP002",["B"],RegionRoleType.Metadata,"@id",2,true));TranslationMappingV2.Apply(d,new Dictionary<string,string>{{"GRP001","译文"}},1);A(a.TranslationText=="译文"&&b.TranslationText=="@id","mapping failed");});
        T("Unknown API id remains rejected",()=>{var d=new RecognitionDocumentV2{TranslationGeneration=1};d.Regions.Add(R("A","GRP001",false));d.TranslationUnits.Add(new("GRP001",["A"],RegionRoleType.BodyParagraph,"source",1,false));try{TranslationMappingV2.Apply(d,new Dictionary<string,string>{{"GRP001","译"},{"UNKNOWN","x"}},1);throw new Exception("accepted");}catch(BatchJsonException){}});
        T("Region decision distinguishes no translation",()=>{using var source=new Bitmap(180,70);var d=new RecognitionDocumentV2();var r=R("A","GRP001",false);d.Regions.Add(r);d.TranslationUnits.Add(new("GRP001",["A"],r.RoleType,"source",1,false));var x=RegionRendererV2.Render(source,d.Regions,new RenderSettings());using var image=x.Bitmap;var row=RegionRenderDecisionAudit.Build(d,x).Single();A(row.Stage=="TranslationMapping"&&row.Code=="NoTranslationText"&&!row.AtomicCommitted,"wrong decision");});
        T("Region decision distinguishes unsafe atomic abort",()=>{using var source=new Bitmap(260,100);using(var g=Graphics.FromImage(source)){g.Clear(Color.Black);for(var i=0;i<1000;i++)source.SetPixel(i%260,i/260,Color.FromArgb((i*71)%255,(i*31)%255,(i*17)%255));}var d=new RecognitionDocumentV2();var r=R("A","GRP001",false);r.TranslationText="可读译文";r.Polygon=GeometryV2.RectanglePolygon(new(5,5,240,80));r.SourceLinePolygons=[GeometryV2.RectanglePolygon(new(5,5,240,80))];d.Regions.Add(r);d.TranslationUnits.Add(new("GRP001",["A"],r.RoleType,"source",1,false));var x=RegionRendererV2.Render(source,d.Regions,new RenderSettings());using var image=x.Bitmap;var row=RegionRenderDecisionAudit.Build(d,x).Single();A(row.AtomicCommitted||row.Stage=="BackgroundIntegration"||row.Stage=="Layout","decision missing");});
        T("Repeated UI font changes keep ComboBox metrics valid",()=>{using var form=new Form();var flow=new FlowLayoutPanel{Dock=DockStyle.Fill};var combo=new ComboBox();flow.Controls.Add(combo);form.Controls.Add(flow);for(var i=0;i<50;i++){FontManager.ApplyUi(form,new ApiSettings{UiFontMode=UiFontMode.Custom,UiFontFamily=i%2==0?"Segoe UI":"Definitely Missing Font",UiFontSize=8+i%8});flow.PerformLayout();_ = combo.PreferredHeight;_ = combo.Font.GetHeight();}A(combo.PreferredHeight>0,"invalid height");});
        T("UI font does not overwrite preview text scope",()=>{using var form=new Form();using var text=new RichTextBox();form.Controls.Add(text);FontManager.ApplyPreviewText(text,new ApiSettings{PreviewTextFontMode=PreviewTextFontMode.Custom,PreviewTextFontFamily="Segoe UI",PreviewTextFontSize=17});var before=(text.Font.Name,text.Font.Size);FontManager.ApplyUi(form,new ApiSettings{UiFontMode=UiFontMode.Custom,UiFontFamily="Microsoft YaHei UI",UiFontSize=9});A(text.Font.Name==before.Name&&Math.Abs(text.Font.Size-before.Size)<.1,"scope contaminated");});
        T("Three typography profiles persist independently",()=>{var s=new ApiSettings{UiFontMode=UiFontMode.Custom,UiFontFamily="Segoe UI",UiFontSize=9,PreviewTextFontMode=PreviewTextFontMode.Custom,PreviewTextFontFamily="Microsoft YaHei UI",PreviewTextFontSize=15,OverlayFontMode=OverlayFontMode.Custom,OverlayFontFamily="Microsoft YaHei",OverlayFontSize=23};var copy=ApiSettingsSnapshot.Copy(s);A(FontManager.ResolveUiProfile(copy).Size==9&&FontManager.ResolvePreviewProfile(copy).Size==15&&FontManager.ResolveTranslationImageProfile(copy).Size==23,"profiles coupled");});
        File.WriteAllText(Path.Combine(output,"repair-063-results.txt"),log+$"TOTAL {pass+fail} PASS {pass} FAIL {fail}{Environment.NewLine}");return fail==0?0:1;
    }

    private static RecognitionRegion R(string id,string unit,bool preserve)=>new(){RegionId=id,TranslationUnitId=unit,RoleType=RegionRoleType.BodyParagraph,Polygon=GeometryV2.RectanglePolygon(new(10,10,140,40)),SourceLinePolygons=[GeometryV2.RectanglePolygon(new(10,10,140,40))],SourceBlockIds=[id],StructuredText="source",PreserveOriginal=preserve,CoverageValid=true};
}
