namespace ScreenshotTranslationUiTester;

public static class VisionV2SelfTests
{
    public static int Run(string outputPath)
    {
        var results = new List<string>(); int pass = 0, fail = 0;
        void Test(string name, Action action) { Console.WriteLine($"RUN {name}");try { action(); results.Add($"PASS {name}"); pass++; } catch (Exception ex) { results.Add($"FAIL {name}: {ex.Message}"); fail++; } }
        static void Assert(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
        RecognitionRegion R(string id, RectangleF b, string text = "text") => new() { RegionId = id, Polygon = GeometryV2.RectanglePolygon(b), StructuredText = text, CorrectedText = text };
        RecognitionRegion L(string id, RectangleF b, string text) { var r=R(id,b,text); var block=new OcrEngineBlock { Id=id, RawText=text, CorrectedText=text, BoundingBox=b, Polygon=GeometryV2.RectanglePolygon(b), Enabled=true }; r.SourceBlockIds=[id]; r.DetectedBlocks=[block]; r.SourceLinePolygons=[block.Polygon]; return r; }
        void WithMain(Action<MainForm> action){var path=Path.Combine(Path.GetTempPath(),$"st-main-{Guid.NewGuid():N}.json");ConfigurationManager.Save(path,new ApiSettings{VisualModel=VisualModelKind.Off});try{var main=new MainForm(path);main.Show();action(main);main.Hide();main.Dispose();}finally{if(File.Exists(path))File.Delete(path);if(File.Exists(path+".bak"))File.Delete(path+".bak");}}

        Test("Visual models are independent explicit choices", () => Assert(VisualModelUiMapping.Options.Length == 7 && VisualModelUiMapping.Options.All(x => x.Label.Contains('（') || x.Kind == VisualModelKind.Off), "model labels"));
        Test("Polygon-first geometry", () => Assert(GeometryV2.Bounds([new(0, 0), new(9, 2), new(7, 8)]).Width == 9, "polygon bounds"));
        Test("OCR retained when visual misses", () => { var o = new OcrEngineBlock { Id = "B1", RawText = "hello", BoundingBox = new(10, 10, 50, 20), Enabled = true }; Assert(RegionProposalFusion.Fuse([], [], [o], 1).Single().SourceBlockIds.Contains("B1"), "OCR lost"); });
        Test("Visual-only semantic region retained for crop OCR", () => { var v = new VisualRegion { Polygon = GeometryV2.RectanglePolygon(new(0, 0, 40, 20)), VisualRoleHint = RegionRoleType.Dialogue, Confidence = .9f }; Assert(RegionProposalFusion.Fuse([], [v], [], 1).Single().DetectedBlocks.Count == 0, "visual lost"); });
        Test("Visual-only unknown image region excluded", () => { var v = new VisualRegion { Polygon = GeometryV2.RectanglePolygon(new(0, 0, 40, 20)), VisualRoleHint = RegionRoleType.Unknown, Confidence = .9f }; Assert(RegionProposalFusion.Fuse([], [v], [], 1).Count == 0, "unknown region leaked"); });
        Test("Overlapping sources fuse", () => { var v = new VisualRegion { Polygon = GeometryV2.RectanglePolygon(new(10, 10, 50, 20)), Confidence = .9f }; var o = new OcrEngineBlock { Id = "B", RawText = "x", BoundingBox = new(10, 10, 50, 20), Enabled = true }; Assert(RegionProposalFusion.Fuse([], [v], [o], 1).Count == 1, "not fused"); });
        Test("Far regions do not merge", () => { var a = new OcrEngineBlock { Id = "A", RawText = "a", BoundingBox = new(0, 0, 20, 10), Enabled = true }; var b = new OcrEngineBlock { Id = "B", RawText = "b", BoundingBox = new(200, 200, 20, 10), Enabled = true }; Assert(RegionProposalFusion.Fuse([], [], [a, b], 1).Count == 2, "merged"); });
        Test("Username role", () => Assert(RegionRoleClassifierV2.Classify(R("A", new(0, 0, 50, 10), "@imsober"), []).Role == RegionRoleType.CharacterName, "role"));
        Test("Metadata role", () => Assert(RegionRoleClassifierV2.Classify(R("A", new(0, 0, 50, 10), "26K views"), []).Role == RegionRoleType.Metadata, "role"));
        Test("Chinese relative-time metadata role", () => Assert(RegionRoleClassifierV2.Classify(R("A", new(0, 0, 80, 10), "\u5927\u7ea6 2 \u5c0f\u65f6\u524d"), []).Role == RegionRoleType.Metadata, "role"));
        Test("Chinese message-count metadata role", () => Assert(RegionRoleClassifierV2.Classify(R("A", new(0, 0, 80, 10), "43 \u6761\u6d88\u606f"), []).Role == RegionRoleType.Metadata, "role"));
        Test("Game button role", () => Assert(RegionRoleClassifierV2.Classify(R("A", new(0, 0, 50, 10), "Continue"), []).Role == RegionRoleType.Button, "role"));
        Test("Game choice role", () => Assert(RegionRoleClassifierV2.Classify(R("A", new(0, 0, 50, 10), "Tell the truth"), []).Role == RegionRoleType.Choice, "role"));
        Test("Top large card heading role", () => { var title=R("T",new(10,5,300,42),"The Mouth in the Hole of the wall"); var body=R("B",new(160,70,300,24),"You moved into a cheap apartment"); Assert(RegionRoleClassifierV2.Classify(title,[title,body]).Role==RegionRoleType.Title,"role"); });
        Test("Narrow card seven wrapped lines become one semantic region", () => { var lines=new[]{"Your childhood","best friend","disappeared for","years... now she's","back as one of","Japan's biggest","celebrities."}.Select((x,i)=>L($"L{i}",new(100,100+i*24,180,20),x)).ToArray(); var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==1 && grouped[0].SourceBlockIds.Count==7,"under-grouped"); });
        Test("Game name remains separate from wrapped dialogue", () => { var lines=new[]{L("N",new(20,10,70,20),"Alice"),L("D1",new(20,40,330,20),"\"Well well well, I see you haven't"),L("D2",new(20,64,340,20),"changed at all since high school. Still a"),L("D3",new(20,88,100,20),"wimp.\"")}; var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==2 && grouped[1].SourceBlockIds.Count==3,"dialogue grouping"); var role=RegionRoleClassifierV2.Classify(grouped[1],grouped); Assert(role.Role==RegionRoleType.Dialogue,"dialogue role"); });
        Test("Rapid-only large heading stays separate from smaller caption", () => { var lines=new[]{L("T",new(68,67,284,28),"Bitchy Ex | April Torres"),L("C",new(61,116,179,18),"Your bitchy ex-gf is back in your life")}; var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==2,"heading and caption merged without PP-S"); });
        Test("April paragraph gaps prevent page over-grouping", () => { var lines=new[]{L("T",new(20,10,80,22),"April"),L("H",new(20,45,350,20),"18:30 | August 01, 2026 | April's Dorm Room"),L("A1",new(20,80,420,20),"April somehow convinced Yan Yi"),L("A2",new(20,104,430,20),"to stay for the evening and talk."),L("D1",new(20,160,400,20),"\"Fuuuck...\" she breathed"),L("D2",new(20,184,380,20),"and closed her eyes."),L("B1",new(20,240,350,20),"And she was right about one thing."),L("B2",new(20,264,330,20),"Nothing would be the same.")}; var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==5 && grouped.Count(x=>x.SourceBlockIds.Count==2)==3,"paragraph boundaries"); });
        Test("Magazine distant columns remain isolated", () => { var lines=new[]{L("A1",new(10,100,150,20),"Left column begins"),L("A2",new(10,124,150,20),"and continues here."),L("B1",new(350,100,150,20),"Right column begins"),L("B2",new(350,124,150,20),"and continues here.")}; var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==2 && grouped.All(x=>x.SourceBlockIds.Count==2),"cross-column merge"); });
        Test("Magazine vertical decorative title merges", () => { var lines=new[]{L("T",new(20,100,90,55),"TIME"),L("I",new(20,180,70,55),"IS"),L("N",new(20,260,100,55),"NOW")}; var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==1&&grouped[0].SourceBlockIds.Count==3,"decorative fragmentation"); });
        Test("Local paragraph gap splits two complete prose blocks", () => { var lines=new[]{L("A1",new(20,10,420,20),"Well, well, well... she opened the door,"),L("A2",new(20,34,430,20),"and looked at him."),L("A3",new(20,58,400,20),"Look who actually showed up."),L("B1",new(20,96,430,20),"She stepped back and opened the door wider,"),L("B2",new(20,120,420,20),"then crooked a finger at him."),L("B3",new(20,144,390,20),"Get in before someone sees me.")}; var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==2&&grouped.All(x=>x.SourceBlockIds.Count==3),"paragraph over-grouping"); });
        Test("Eight ordinary wrapped lines remain one paragraph", () => { var lines=Enumerable.Range(0,8).Select(i=>L($"W{i}",new(20,10+i*24,420-(i%3)*20,20),i==7?"the final wrapped line.":$"ordinary wrapped content line {i}")).ToArray(); var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==1&&grouped[0].SourceBlockIds.Count==8,"wrapped lines split"); });
        Test("Narration and quote in one visual paragraph stay together", () => { var lines=new[]{L("N1",new(20,10,420,20),"She looked at him. \"Come here,\""),L("N2",new(20,34,360,20),"she said without looking away.")}; Assert(SemanticRegionGrouperV2.Group(lines,1).Count==1,"quote-only split"); });
        Test("Large gap separates dialogue and narration paragraphs", () => { var lines=new[]{L("D1",new(20,10,420,20),"\"What do you think?\" she asked."),L("D2",new(20,34,380,20),"He did not answer her."),L("N1",new(20,78,420,20),"Once he was inside, she closed the door."),L("N2",new(20,102,380,20),"The room became quiet.")}; var grouped=SemanticRegionGrouperV2.Group(lines,1); Assert(grouped.Count==2,"dialogue boundary merged"); });
        Test("Semantic region preserves source line polygons", () => { var grouped=SemanticRegionGrouperV2.Group([L("A",new(0,0,80,10),"wrapped line"),L("B",new(0,12,80,10),"continues.")],1).Single(); Assert(grouped.SourceLinePolygons.Count==2 && grouped.SourceBlockIds.SequenceEqual(["A","B"]),"line geometry lost"); });
        Test("Safe target never unions incompatible roles",()=>{var a=L("TITLE",new(10,10,260,22),"Card title");a.RoleType=RegionRoleType.Title;var b=L("QUOTE",new(150,36,180,20),"\"Dialogue\"");b.RoleType=RegionRoleType.Dialogue;Assert(SemanticRegionGrouperV2.Group([a,b],1).Count==2,"incompatible roles unioned");});
        Test("Safe target rejects disconnected geometry union",()=>{var r=L("A",new(10,10,100,20),"first");r.SourceBlockIds.Add("B");r.SourceLinePolygons.Add(GeometryV2.RectanglePolygon(new(300,120,100,20)));r.DetectedBlocks.Add(new OcrEngineBlock{Id="B",RawText="second",CorrectedText="second",BoundingBox=new(300,120,100,20),Polygon=GeometryV2.RectanglePolygon(new(300,120,100,20)),Enabled=true});r.TranslationText="完整译文";Assert(SafeLayoutTargetPlanner.Plan(r).Status==SafeLayoutTargetStatus.UnsafeStructureTarget,"disconnected union accepted");});
        Test("Safe target rejects image exclusion intrusion",()=>{var r=L("A",new(10,10,300,30),"heading");r.RendererTargetRegion=new(10,10,300,100);var exclusion=new RectangleF(20,45,140,60);r.LayoutExclusionPolygons=[GeometryV2.RectanglePolygon(exclusion)];var d=SafeLayoutTargetPlanner.Plan(r);Assert(d.Status==SafeLayoutTargetStatus.Safe&&d.Targets.All(x=>RectangleF.Intersect(x,exclusion).IsEmpty),"image intrusion accepted");});
        Test("Safe target keeps adjacent multiline paragraph",()=>{var lines=Enumerable.Range(0,5).Select(i=>{var r=L($"P{i}",new(20,20+i*24,300,20),$"paragraph line {i}");r.RoleType=RegionRoleType.BodyParagraph;return r;}).ToArray();var grouped=SemanticRegionGrouperV2.Group(lines,1);Assert(grouped.Count==1&&SafeLayoutTargetPlanner.Plan(grouped[0]).Status==SafeLayoutTargetStatus.Safe,"normal paragraph fragmented");});
        Test("Safe target leaves translation characters unchanged",()=>{using var b=new Bitmap(320,100);var r=L("A",new(10,10,280,70),"source");r.TranslationText="逐字符 ABC 123，不得改变。";var before=r.TranslationText;var x=RegionRendererV2.Render(b,[r],new RenderSettings());using var image=x.Bitmap;Assert(r.TranslationText==before&&string.Concat(x.Diagnostics!.Single().RenderedLines.Select(y=>y.Text))==before,"translation content changed");});
        Test("Disconnected target never guesses segment mapping",()=>{var r=L("A",new(10,10,100,20),"first");r.SourceBlockIds.Add("B");r.SourceLinePolygons.Add(GeometryV2.RectanglePolygon(new(250,90,100,20)));r.TranslationText="only whole translation";var d=SafeLayoutTargetPlanner.Plan(r);Assert(!d.HasReliableSegmentMapping&&d.Targets.Count==0,"guessed segment mapping");});
        Test("Unsafe target uses explicit translation-first fallback",()=>{using var b=new Bitmap(360,140);using(var g=Graphics.FromImage(b))g.Clear(Color.FromArgb(17,33,55));var r=L("A",new(10,10,100,20),"first");r.SourceBlockIds.Add("B");r.SourceLinePolygons.Add(GeometryV2.RectanglePolygon(new(250,90,100,20)));r.DetectedBlocks.Add(new OcrEngineBlock{Id="B",RawText="second",BoundingBox=new(250,90,100,20),Polygon=GeometryV2.RectanglePolygon(new(250,90,100,20)),Enabled=true});r.TranslationText="译文";var x=RegionRendererV2.Render(b,[r],new RenderSettings());using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(d.FallbackAttempted&&d.FallbackRendered&&d.AtomicRegionCommitted&&string.Concat(d.RenderedLines.Select(y=>y.Text))==r.TranslationText,"unsafe target did not use complete fallback");});
        Test("Safe planning preserves SourceRegionRect",()=>{var r=L("A",new(12,14,120,24),"source");var original=r.SourceImageRegion=r.BoundingBox;r.RendererTargetRegion=new(5,5,200,60);_ = SafeLayoutTargetPlanner.Plan(r);Assert(r.SourceImageRegion==original&&r.BoundingBox==original,"source rect mutated");});
        Test("Geometry islands retain Region and SourceBlock trace",()=>{var a=L("A",new(10,10,100,20),"one");a.SourceBlockIds.Add("B");a.SourceLinePolygons.Add(GeometryV2.RectanglePolygon(new(260,80,100,20)));var d=SafeLayoutTargetPlanner.Plan(a);Assert(d.Islands.SelectMany(x=>x.SourceBlockIds).Order().SequenceEqual(["A","B"]),"trace ids lost");});
        Test("Failed structure validation commits fallback atomically",()=>{using var b=new Bitmap(260,100);using(var g=Graphics.FromImage(b)){g.Clear(Color.Navy);g.FillRectangle(Brushes.Gold,20,20,30,30);}var r=L("A",new(10,10,80,20),"first");r.SourceBlockIds.Add("B");r.SourceLinePolygons.Add(GeometryV2.RectanglePolygon(new(180,70,60,20)));r.TranslationText="中文";var x=RegionRendererV2.Render(b,[r],new RenderSettings{BackgroundStrategy=TranslationOverlayBackgroundStyle.Solid});using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(d.FallbackRendered&&d.AtomicRegionCommitted&&d.TextDrawCount==1,"fallback transaction was not atomic");});
        Test("Phase 1.1 original overlap preserved",()=>{var r=L("R001",new(51,19,518,29),"title");r.RoleType=RegionRoleType.Title;var exclusion=new RectangleF(21.93f,33.03f,215.45f,261.91f);r.LayoutExclusionPolygons=[GeometryV2.RectanglePolygon(exclusion)];var d=SafeLayoutTargetPlanner.Plan(r);var m=SafeLayoutTargetPlanner.AnalyzeImageIntrusion(d.Targets.Single(),[r.BoundingBox],exclusion);Assert(d.Status==SafeLayoutTargetStatus.Safe&&m.SourceImageOverlapArea>0&&m.AddedIntrusionArea==0,"legitimate overlap removed or rejected");});
        Test("Phase 1.1 added image intrusion is zero",()=>{var r=L("A",new(10,10,100,20),"line one");r.RoleType=RegionRoleType.BodyParagraph;var b=L("B",new(10,50,100,20),"line two");b.RoleType=RegionRoleType.BodyParagraph;r.SourceBlockIds.AddRange(b.SourceBlockIds);r.SourceLinePolygons.AddRange(b.SourceLinePolygons);r.DetectedBlocks.AddRange(b.DetectedBlocks);var exclusion=new RectangleF(10,30,100,20);r.LayoutExclusionPolygons=[GeometryV2.RectanglePolygon(exclusion)];Assert(SafeLayoutTargetPlanner.Plan(r).Status==SafeLayoutTargetStatus.UnsafeStructureTarget,"new intrusion accepted");});
        Test("Phase 1.1 dialogue image intrusion is zero",()=>{var r=L("R002",new(257,50,309,70),"dialogue");r.RoleType=RegionRoleType.Dialogue;var exclusion=new RectangleF(21.93f,33.03f,215.45f,261.91f);r.LayoutExclusionPolygons=[GeometryV2.RectanglePolygon(exclusion)];var d=SafeLayoutTargetPlanner.Plan(r);var m=SafeLayoutTargetPlanner.AnalyzeImageIntrusion(d.Targets.Single(),[r.BoundingBox],exclusion);Assert(d.Status==SafeLayoutTargetStatus.Safe&&m.NewTargetImageOverlapArea==0&&m.AddedIntrusionArea==0,"dialogue entered image");});
        Test("Phase 1.1 independent TranslationUnits share one batch",()=>{var units=new[]{new TranslationUnitV2("GRP001",["T"],RegionRoleType.Title,"title",1,false),new TranslationUnitV2("GRP002",["D"],RegionRoleType.Dialogue,"dialogue",2,false),new TranslationUnitV2("GRP003",["H"],RegionRoleType.Header,"header",3,false)};var items=units.Select(x=>new TranslationItem(x.Id,x.Text,x.RoleType switch{RegionRoleType.Title=>StructuredTextRole.Title,RegionRoleType.Dialogue=>StructuredTextRole.Dialogue,RegionRoleType.Header=>StructuredTextRole.Header,_=>StructuredTextRole.Unknown})).ToArray();var json=TranslationService.BuildStructuredInputForTest(items);using var doc=System.Text.Json.JsonDocument.Parse(json);Assert(doc.RootElement.GetArrayLength()==3&&doc.RootElement.EnumerateArray().Select(x=>x.GetProperty("id").GetString()).SequenceEqual(["GRP001","GRP002","GRP003"]),"units not serialized in one batch");});
        Test("Phase 1.1 renderer guess split is false",()=>{var r=L("A",new(10,10,80,20),"one");r.SourceBlockIds.Add("B");r.SourceLinePolygons.Add(GeometryV2.RectanglePolygon(new(220,80,80,20)));r.TranslationText="one whole translation";var d=SafeLayoutTargetPlanner.Plan(r);Assert(d.Status==SafeLayoutTargetStatus.UnsafeStructureTarget&&d.Targets.Count==0&&!d.HasReliableSegmentMapping,"renderer split was guessed");});
        Test("Phase 1.1 unsafe mapping keeps full translation in fallback",()=>{using var source=new Bitmap(320,120);using(var g=Graphics.FromImage(source)){g.Clear(Color.FromArgb(31,47,63));g.FillEllipse(Brushes.Orange,20,20,45,45);}var r=L("A",new(10,10,80,20),"one");r.SourceBlockIds.Add("B");r.SourceLinePolygons.Add(GeometryV2.RectanglePolygon(new(220,80,80,20)));r.TranslationText="translation";var rendered=RegionRendererV2.Render(source,[r],new RenderSettings());using var output=rendered.Bitmap;var d=rendered.Diagnostics!.Single();Assert(d.FallbackRendered&&string.Concat(d.RenderedLines.Select(x=>x.Text))==r.TranslationText,"unsafe mapping lost translation");});
        Test("Preview region debug labels default hidden", () => { using var image=new Bitmap(160,80); using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings { VisualModel=VisualModelKind.Off },new OcrService(),new TranslationService()); Assert(!form.RegionLabelsVisibleForSmoke,"labels visible"); });
        Test("Fresh Preview has every debug layer off", () => { using var image=new Bitmap(160,80); using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings { VisualModel=VisualModelKind.Off },new OcrService(),new TranslationService()); Assert(form.VisibleV2LayerCountForSmoke==0,"debug layer enabled"); });
        Test("MainNavigation 20 loops has no blank page",()=>WithMain(main=>{for(var loop=0;loop<20;loop++)foreach(var name in MainForm.MainPageNamesForSmoke)Assert(main.NavigateForSmoke(name),$"blank {name} loop {loop}");Assert(main.MainHostControlCountForSmoke==3,"host lost pages");}));
        Test("MainNavigation random 100 has no blank page",()=>WithMain(main=>{var random=new Random(424);for(var i=0;i<100;i++){var name=MainForm.MainPageNamesForSmoke[random.Next(MainForm.MainPageNamesForSmoke.Length)];Assert(main.NavigateForSmoke(name),$"blank random {i} {name}");}}));
        Test("Settings tabs 30 loops have content",()=>WithMain(main=>{for(var loop=0;loop<30;loop++)for(var i=0;i<main.SettingsTabCountForSmoke;i++)Assert(main.SettingsTabAliveForSmoke(i),$"blank settings tab {i} loop {loop}");}));
        Test("Settings leave and return 20 loops remains alive",()=>WithMain(main=>{for(var i=0;i<20;i++){Assert(main.NavigateForSmoke("设置"),"settings blank");Assert(main.SettingsTabAliveForSmoke(i%main.SettingsTabCountForSmoke),"tab blank");Assert(main.NavigateForSmoke("主页"),"home page blank");}}));
        Test("After Preview close all main pages remain alive",()=>WithMain(main=>{using var image=new Bitmap(180,90);using var preview=main.OpenPreviewForSmoke(image);preview.Close();foreach(var name in MainForm.MainPageNamesForSmoke)Assert(main.NavigateForSmoke(name),$"after preview blank {name}");}));
        Test("After Settings save current page remains alive",()=>WithMain(main=>{Assert(main.NavigateForSmoke("设置"),"settings blank before save");main.SaveSettingsForSmoke();Assert(main.NavigateForSmoke("设置")&&main.SettingsTabAliveForSmoke(0),"settings blank after save");}));
        Test("After appearance refresh every page remains alive",()=>WithMain(main=>{main.RefreshAppearanceForSmoke();foreach(var name in MainForm.MainPageNamesForSmoke)Assert(main.NavigateForSmoke(name),$"appearance blank {name}");}));
        Test("Minimize restore preserves page host",()=>WithMain(main=>{main.WindowState=FormWindowState.Minimized;main.WindowState=FormWindowState.Normal;Assert(main.NavigateForSmoke("设置")&&main.SettingsTabAliveForSmoke(4),"restore blank");}));
        Test("Default translated shows translated when render completes",()=>{using var source=new Bitmap(200,100);using var translated=new Bitmap(200,100);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Translated,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());Assert(form.ImageViewForSmoke==ImageViewMode.Translated&&form.DisplayedImageViewForSmoke==ImageViewMode.Original&&form.ImageModeTextForSmoke.Contains("生成中"),"initial fallback state");form.SetTranslatedDisplayForSmoke(translated);Assert(form.DisplayedImageViewForSmoke==ImageViewMode.Translated&&form.ImageModeTextForSmoke=="译图（实验）","render completion did not switch");});
        Test("Default original stays original after render",()=>{using var source=new Bitmap(200,100);using var translated=new Bitmap(200,100);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Original,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetTranslatedDisplayForSmoke(translated);Assert(form.ImageViewForSmoke==ImageViewMode.Original&&form.DisplayedImageViewForSmoke==ImageViewMode.Original,"default original changed");});
        Test("User original during translation remains original",()=>{using var source=new Bitmap(200,100);using var translated=new Bitmap(200,100);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Translated,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetPreviewSelectionForSmoke(OcrEngineKind.Rapid,ImageViewMode.Original,TextViewMode.Organized);form.SetTranslatedDisplayForSmoke(translated);Assert(form.DisplayedImageViewForSmoke==ImageViewMode.Original,"user original overridden");});
        Test("User translated during translation displays when ready",()=>{using var source=new Bitmap(200,100);using var translated=new Bitmap(200,100);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Original,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetPreviewSelectionForSmoke(OcrEngineKind.Rapid,ImageViewMode.Translated,TextViewMode.Translation);Assert(form.DisplayedImageViewForSmoke==ImageViewMode.Original&&form.ImageModeTextForSmoke.Contains("生成中"),"temporary fallback unclear");form.SetTranslatedDisplayForSmoke(translated);Assert(form.DisplayedImageViewForSmoke==ImageViewMode.Translated,"user translated not honored");});
        Test("Retranslate preserves translated preferred mode",()=>{using var source=new Bitmap(200,100);using var first=new Bitmap(200,100);using var second=new Bitmap(200,100);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Translated,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetTranslatedDisplayForSmoke(first);form.SetTranslatedDisplayForSmoke(null,"Retranslation");form.SetTranslatedDisplayForSmoke(second,"RendererCompleted");Assert(form.ImageViewForSmoke==ImageViewMode.Translated&&form.DisplayedImageViewForSmoke==ImageViewMode.Translated,"retranslation reset view");});
        Test("OCR rerun returns to translated preferred mode",()=>{using var source=new Bitmap(200,100);using var translated=new Bitmap(200,100);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Translated,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetTranslatedDisplayForSmoke(null,"OCRRerun");form.SetTranslatedDisplayForSmoke(translated,"RendererCompleted");Assert(form.DisplayedImageViewForSmoke==ImageViewMode.Translated,"OCR rerun reset view");});
        Test("Appearance refresh keeps translated mode",()=>{using var source=new Bitmap(200,100);using var translated=new Bitmap(200,100);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Translated,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetTranslatedDisplayForSmoke(translated);form.ApplyAppearanceSettings(new ApiSettings{OverlayBackgroundStyle=TranslationOverlayBackgroundStyle.Solid});Assert(form.DisplayedImageViewForSmoke==ImageViewMode.Translated,"appearance reset view");});
        Test("Remember last selection overrides default",()=>{using var source=new Bitmap(200,100);using var translated=new Bitmap(200,100);var session=new SessionServices();session.RememberPreviewSelection(OcrEngineKind.Rapid,ImageViewMode.Translated,TextViewMode.Translation);var ocr=new OcrRuntimeManager(AppContext.BaseDirectory,new OcrService());var vision=new VisionRuntimeManager(AppContext.BaseDirectory);try{using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Original,RememberLastPreviewSelection=true,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService(),ocr,vision,session);form.SetTranslatedDisplayForSmoke(translated);Assert(form.ImageViewForSmoke==ImageViewMode.Translated&&form.DisplayedImageViewForSmoke==ImageViewMode.Translated,"remember priority lost");}finally{vision.DisposeAsync().AsTask().GetAwaiter().GetResult();ocr.DisposeAsync().AsTask().GetAwaiter().GetResult();session.Dispose();}});
        Test("Combo and displayed image remain synchronized",()=>{using var source=new Bitmap(200,100);using var translated=new Bitmap(200,100);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Translated,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());Assert(form.ImageModeTextForSmoke=="译图（实验·生成中）"&&form.DisplayedImageViewForSmoke==ImageViewMode.Original,"fallback not explicit");form.SetTranslatedDisplayForSmoke(translated);Assert(form.ImageModeTextForSmoke=="译图（实验）"&&form.DisplayedImageViewForSmoke==ImageViewMode.Translated,"combo canvas mismatch");});
        Test("After Screenshot all main pages remain alive",()=>WithMain(main=>{Assert(main.NavigateForSmoke("主页"),"home page unavailable");foreach(var page in MainForm.MainPageNamesForSmoke)Assert(main.NavigateForSmoke(page),$"{page} blank after screenshot workflow");}));
        Test("Default translated 10 consecutive previews finish translated",()=>{for(var i=0;i<10;i++){using var source=new Bitmap(120,60);using var translated=new Bitmap(120,60);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Translated,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetTranslatedDisplayForSmoke(translated,"RendererCompleted");Assert(form.ImageViewForSmoke==ImageViewMode.Translated&&form.DisplayedImageViewForSmoke==ImageViewMode.Translated,$"iteration {i+1}");}});
        Test("Default original 5 consecutive previews stay original",()=>{for(var i=0;i<5;i++){using var source=new Bitmap(120,60);using var translated=new Bitmap(120,60);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Original,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetTranslatedDisplayForSmoke(translated,"RendererCompleted");Assert(form.ImageViewForSmoke==ImageViewMode.Original&&form.DisplayedImageViewForSmoke==ImageViewMode.Original,$"iteration {i+1}");}});
        Test("Preview minimize restore preserves selected mode",()=>{using var source=new Bitmap(160,80);using var translated=new Bitmap(160,80);using var form=new PreviewForm(source,PreviewMode.OcrOnly,new ApiSettings{PreviewDefaultImage=PreviewDefaultImage.Translated,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.SetTranslatedDisplayForSmoke(translated);form.Show();form.WindowState=FormWindowState.Minimized;form.WindowState=FormWindowState.Normal;Assert(form.ImageViewForSmoke==ImageViewMode.Translated&&form.DisplayedImageViewForSmoke==ImageViewMode.Translated,"preview mode lost after restore");form.Hide();form.Dispose();});
        Test("Settings dark theme has no contrast hazard",()=>WithMain(main=>{main.NavigateForSmoke("设置");var issues=main.ThemeContrastIssuesForSmoke();Assert(issues.Count==0,string.Join(" | ",issues));}));
        Test("All visible buttons fit Chinese text",()=>WithMain(main=>{main.NavigateForSmoke("设置");var issues=main.ButtonClipIssuesForSmoke();Assert(issues.Count==0,string.Join(" | ",issues));}));
        Test("Dialog buttons fit at 100 125 150 percent",()=>{foreach(var scale in new[]{1f,1.25f,1.5f}){using var translation=new TranslationSettingsDialog(new ApiSettings());translation.Show();translation.Scale(new SizeF(scale,scale));translation.PerformLayout();var issues=MainForm.AuditButtons(translation);translation.Close();Assert(issues.Count==0,$"translation {scale}: {string.Join(" | ",issues)}");using var appearance=new AppearanceSettingsDialog(new ApiSettings());appearance.Show();appearance.Scale(new SizeF(scale,scale));appearance.PerformLayout();issues=MainForm.AuditButtons(appearance);appearance.Close();Assert(issues.Count==0,$"appearance {scale}: {string.Join(" | ",issues)}");}});
        Test("Detached main page safe recovery preserves host",()=>WithMain(main=>{main.NavigateForSmoke("历史");Assert(main.RecoverDetachedMainPageForSmoke(),main.CurrentPageDiagnosticForSmoke());Assert(main.NavigateForSmoke("历史"),"recovered page blank");}));
        Test("Detached settings root safe recovery",()=>WithMain(main=>{for(var i=0;i<main.SettingsTabCountForSmoke;i++)Assert(main.RecoverDetachedSettingsRootForSmoke(i),$"tab {i}");}));
        Test("Settings theme and host combined 20 loops",()=>WithMain(main=>{for(var loop=0;loop<20;loop++){main.NavigateForSmoke("设置");for(var i=0;i<main.SettingsTabCountForSmoke;i++)Assert(main.SettingsTabAliveForSmoke(i),$"before theme {loop}:{i}");main.RefreshAppearanceForSmoke();for(var i=0;i<main.SettingsTabCountForSmoke;i++)Assert(main.SettingsTabAliveForSmoke(i),$"after theme {loop}:{i}");main.SaveSettingsForSmoke();for(var i=0;i<main.SettingsTabCountForSmoke;i++)Assert(main.SettingsTabAliveForSmoke(i),$"after save {loop}:{i}");}}));
        Test("Theme does not change toolbar control size",()=>{using var root=new FlowLayoutPanel();using var button=new Button{Text="重新识别 OCR",Size=new(111,34),MinimumSize=new(82,34),Padding=new(2),Margin=new(3)};root.Controls.Add(button);var before=(button.Size,button.MinimumSize,button.Padding,button.Margin);UiDarkTheme.Apply(root);Assert(before==(button.Size,button.MinimumSize,button.Padding,button.Margin),"theme changed geometry");});
        Test("Theme does not change preferred size",()=>{using var button=new Button{Text="重新识别 OCR",AutoSize=true};var before=button.GetPreferredSize(Size.Empty);UiDarkTheme.Apply(button);Assert(before==button.GetPreferredSize(Size.Empty),"preferred size changed");});
        Test("Theme does not change control font",()=>{using var root=new Panel();using var combo=new ComboBox();using var button=new Button();root.Controls.AddRange([combo,button]);var a=combo.Font;var b=button.Font;UiDarkTheme.Apply(root);Assert(ReferenceEquals(a,combo.Font)&&ReferenceEquals(b,button.Font),"font replaced");});
        Test("Theme keeps combo native metrics",()=>{using var combo=new ComboBox{DrawMode=DrawMode.Normal,ItemHeight=17,Width=118};var before=(combo.DrawMode,combo.ItemHeight,combo.Width);UiDarkTheme.Apply(combo);Assert(before==(combo.DrawMode,combo.ItemHeight,combo.Width),"combo metrics changed");});
        Test("Tab owner draw keeps native page host",()=>{using var tabs=new DarkTabControl();using var page=new TabPage("历史与缓存");using var content=new Panel();page.Controls.Add(content);tabs.TabPages.Add(page);tabs.CreateControl();tabs.Refresh();Assert(page.Parent==tabs&&page.Controls.Contains(content)&&tabs.DrawMode==TabDrawMode.OwnerDrawFixed,"tab page detached");});
        Test("Overlay toggle does not trigger recognition", () => { using var image=new Bitmap(160,80); using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings { VisualModel=VisualModelKind.Off },new OcrService(),new TranslationService()); var before=form.RecognitionRunCountForSmoke; form.SetV2LayerForSmoke(RegionOverlayLayer.RoleLabels,true); form.SetV2LayerForSmoke(RegionOverlayLayer.RoleLabels,false); Assert(form.RecognitionRunCountForSmoke==before,"recognition rerun"); });
        Test("Text refresh preserves preview scroll", () => { using var image=new Bitmap(300,160); using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings { VisualModel=VisualModelKind.Off },new OcrService(),new TranslationService()); form.Show(); var groups=Enumerable.Range(1,60).Select(i=>new SegmentGroup { GroupId=$"G{i}", GroupType=SegmentType.Body, OriginalText=$"line {i}", OrganizedText=$"line {i}", Translation=$"translated line {i}", Bounds=new(0,i*20,200,18), ReadingOrder=i }).ToList(); form.SetDocumentForSmoke(new OcrDocument { Groups=groups }); form.SetTextViewForSmoke(TextViewMode.Translation); form.ScrollTextLinesForSmoke(30); var before=form.TextFirstVisibleLineForSmoke; form.RefreshTextForSmoke(); var after=form.TextFirstVisibleLineForSmoke; form.Hide();form.Dispose(); Assert(before>0 && Math.Abs(after-before)<=1,$"scroll {before}->{after}"); });
        Test("Stable translation mapping", () => { var d = new RecognitionDocumentV2(); d.TranslationGeneration = 2; d.Regions.Add(R("R1", new(0, 0, 20, 10))); d.TranslationUnits.Add(new("TU001", ["R1"], RegionRoleType.Dialogue, "x", 0, false)); TranslationMappingV2.Apply(d, new Dictionary<string,string>{{"TU001","译"}}, 2); Assert(d.Regions[0].TranslationText == "译", "mapping"); });
        Test("Stale translation discarded", () => { var d = new RecognitionDocumentV2 { TranslationGeneration = 4 }; d.Regions.Add(R("R1", new(0, 0, 20, 10))); d.TranslationUnits.Add(new("TU001", ["R1"], RegionRoleType.Dialogue, "x", 0, false)); TranslationMappingV2.Apply(d, new Dictionary<string,string>{{"TU001","old"}}, 3); Assert(d.Regions[0].TranslationText == "", "stale applied"); });
        Test("Missing ID fails", () => { var d = new RecognitionDocumentV2 { TranslationGeneration = 1 }; d.TranslationUnits.Add(new("TU001", ["R1"], RegionRoleType.Dialogue, "x", 0, false)); try { TranslationMappingV2.Apply(d, new Dictionary<string,string>(), 1); throw new Exception("accepted"); } catch (BatchJsonException) { } });
        Test("Extra ID fails", () => { var d = new RecognitionDocumentV2 { TranslationGeneration = 1 }; try { TranslationMappingV2.Apply(d, new Dictionary<string,string>{{"X","x"}}, 1); throw new Exception("accepted"); } catch (BatchJsonException) { } });
        Test("Preserve original", () => { var d = new RecognitionDocumentV2 { TranslationGeneration = 1 }; var r = R("R1", new(0, 0, 20, 10), "code"); r.PreserveOriginal = true; d.Regions.Add(r); d.TranslationUnits.Add(new("TU001", ["R1"], RegionRoleType.Metadata, "code", 0, true)); TranslationMappingV2.Apply(d, new Dictionary<string,string>{{"TU001","wrong"}}, 1); Assert(r.TranslationText == "code", "not preserved"); });
        Test("V2 TranslationUnit keeps GRP wire IDs", () => { var units = TranslationUnitBuilderV2.Build([R("R1", new(0,0,20,10), "April")]); Assert(units.Single().Id == "GRP001", "wire id changed"); });
        Test("V2 missing=GRP001 targeted recovery", () =>
        {
            static string Envelope(string content) => System.Text.Json.JsonSerializer.Serialize(new { choices = new[] { new { message = new { content } } } });
            var regions = new[] { R("R1", new(0,0,20,10), "April"), R("R2", new(0,20,30,10), "Hello") };
            var units = TranslationUnitBuilderV2.Build(regions);
            var items = units.Select(x => new TranslationItem(x.Id, x.Text, x.RoleType == RegionRoleType.CharacterName ? StructuredTextRole.CharacterName : StructuredTextRole.Dialogue)).ToArray();
            var recovered = TranslationService.RecoverMissingGroupsForTest(items, Envelope("{\"GRP002\":\"你好\"}"), Envelope("{\"GRP001\":\"April\"}"), out var recoveryIds);
            Assert(recoveryIds.SequenceEqual(["GRP001"]) && recovered.Translations.Count == 2 && recovered.RequestCount == 2, "targeted recovery was not isolated");
        });
        Test("V2 recovery still missing fails", () => { static string E(string c) => System.Text.Json.JsonSerializer.Serialize(new { choices = new[] { new { message = new { content = c } } } }); try { TranslationService.RecoverMissingGroupsForTest([new("GRP001","a"),new("GRP002","b")], E("{\"GRP002\":\"B\"}"), E("{}"), out _); throw new Exception("accepted"); } catch (BatchJsonException) { } });
        Test("V2 recovery extra ID fails", () => { static string E(string c) => System.Text.Json.JsonSerializer.Serialize(new { choices = new[] { new { message = new { content = c } } } }); try { TranslationService.RecoverMissingGroupsForTest([new("GRP001","a"),new("GRP002","b")], E("{\"GRP002\":\"B\"}"), E("{\"GRP001\":\"A\",\"GRP999\":\"X\"}"), out _); throw new Exception("accepted"); } catch (BatchJsonException) { } });
        Test("V2 complete response avoids recovery", () => { static string E(string c) => System.Text.Json.JsonSerializer.Serialize(new { choices = new[] { new { message = new { content = c } } } }); var result = TranslationService.RecoverMissingGroupsForTest([new("GRP001","a")], E("{\"GRP001\":\"A\"}"), null, out var ids); Assert(ids.Count == 0 && result.RequestCount == 1, "blind retry"); });
        Test("Editor create delete undo redo", () => { var e = new RegionEditorSession([R("R1", new(0,0,10,10))]); e.Create(GeometryV2.RectanglePolygon(new(20,0,10,10))); Assert(e.Regions.Count == 2, "create"); e.Undo(); Assert(e.Regions.Count == 1, "undo"); e.Redo(); Assert(e.Regions.Count == 2, "redo"); });
        Test("Editor move preserves other IDs", () => { var e = new RegionEditorSession([R("R1", new(0,0,10,10)), R("R2", new(20,0,10,10))]); e.Move("R1", 5, 0); Assert(e.Regions.Any(x => x.RegionId == "R2") && e.Regions.Single(x => x.RegionId == "R1").BoundingBox.X == 5, "identity"); });
        Test("Editor role override survives classification", () => { var e = new RegionEditorSession([R("R1", new(0,0,10,10), "Alice")]); e.SetRole("R1", RegionRoleType.CharacterName); Assert(RegionRoleClassifierV2.Classify(e.Regions[0], e.Regions).Role == RegionRoleType.CharacterName, "override"); });
        Test("Editor merge", () => { var e = new RegionEditorSession([R("R1", new(0,0,10,10)), R("R2", new(20,0,10,10))]); e.Merge(["R1","R2"]); Assert(e.Regions.Count == 1 && e.Regions[0].BoundingBox.Width == 30, "merge"); });
        Test("Editor split", () => { var e = new RegionEditorSession([R("R1", new(0,0,20,10))]); e.Split("R1", [GeometryV2.RectanglePolygon(new(0,0,10,10)), GeometryV2.RectanglePolygon(new(10,0,10,10))]); Assert(e.Regions.Count == 2 && e.Regions.Select(x => x.RegionId).Distinct().Count() == 2, "split"); });
        Test("Editor resize polygon order flags", () => { var e = new RegionEditorSession([R("R1", new(0,0,10,10))]); e.Resize("R1", new(1,2,30,20)); e.EditPolygon("R1", [new(1,2),new(31,3),new(29,22),new(2,21)]); e.SetReadingOrder("R1", 7); e.SetIgnored("R1", true); e.SetPreserveOriginal("R1", true); var x=e.Regions.Single(); Assert(x.Polygon.Length==4 && x.ReadingOrder==7 && x.IsIgnored && x.PreserveOriginal, "editor fields"); });
        Test("Region-only OCR preserves Region ID", () => { var e = new RegionEditorSession([R("R1", new(0,0,10,10))]); e.ReplaceOcr("R1", [new OcrEngineBlock { Id="B9", RawText="retry", CorrectedText="retry", BoundingBox=new(0,0,10,10) }]); Assert(e.Regions.Single().RegionId=="R1" && e.Regions.Single().SourceBlockIds.SequenceEqual(["B9"]), "region identity"); });
        Test("Overflow is explicit or committed without text mutation", () => { using var b = new Bitmap(100,40); var r = R("R1", new(0,0,10,5)); r.TranslationText = new string('X', 500); var result = RegionRendererV2.Render(b, [r], new RenderSettings()); using var rendered = result.Bitmap; var d=result.Diagnostics!.Single();var drawn=string.Concat(d.RenderedLines.Select(x=>x.Text));Assert((d.AtomicRegionCommitted&&drawn==r.TranslationText)||(!d.AtomicRegionCommitted&&d.FallbackAttempted&&d.RenderStatus==RegionRenderStatus.Failed&&d.DecisionCode=="ExplicitRenderFailure"), "overflow was silently truncated or preserved without explicit failure"); });
        Test("Renderer V2 keeps translation fallback inside its Region anchor", () => { using var b=new Bitmap(120,40); using(var g=Graphics.FromImage(b))g.Clear(Color.White); var a=R("A",new(0,0,50,30)); var c=R("B",new(70,0,50,30)); a.TranslationText="A"; var result=RegionRendererV2.Render(b,[a,c],new RenderSettings { BackgroundOpacity=0, Outline=false }); using var rendered=result.Bitmap;var diagnostics=result.Diagnostics!;var d=diagnostics.Single(x=>x.RegionId=="A");Assert(RectangleF.Intersect(d.RenderBounds,c.BoundingBox).IsEmpty&&diagnostics.Single(x=>x.RegionId=="B").AtomicRegionCommitted==false, "cross-region write"); });
        Test("Renderer 2 uses one semantic paragraph for eight source lines", () => { using var b=new Bitmap(500,220); using(var g=Graphics.FromImage(b))g.Clear(Color.White); var r=R("P",new(20,20,450,180)); r.RoleType=RegionRoleType.BodyParagraph; r.SourceBlockIds=Enumerable.Range(1,8).Select(x=>$"L{x}").ToList(); r.SourceLinePolygons=Enumerable.Range(0,8).Select(i=>GeometryV2.RectanglePolygon(new RectangleF(20,20+i*20,440,16))).ToList(); r.TranslationText="你的童年挚友消失多年，如今她回来了，成为日本最红的明星之一。"; var x=RegionRendererV2.Render(b,[r],new RenderSettings()); using var image=x.Bitmap; var d=x.Diagnostics!.Single(); Assert(d.SourceLineCount==8&&d.Coverage.Count==8&&d.Coverage.All(c=>c.Masked)&&d.LineCount<8,"physical-line layout leaked"); });
        Test("Renderer 2 keeps two semantic regions independent", () => { using var b=new Bitmap(400,220); using(var g=Graphics.FromImage(b))g.Clear(Color.White); var a=L("A",new(20,20,350,60),"A"); var c=L("B",new(20,130,350,60),"B"); a.TranslationText="第一段中文。";c.TranslationText="第二段中文。";var x=RegionRendererV2.Render(b,[a,c],new RenderSettings());using var image=x.Bitmap;Assert(x.Diagnostics!.Count==2&&x.Diagnostics.Select(d=>d.RegionId).Distinct().Count()==2,"paragraphs merged"); });
        Test("Renderer 2 centers button and keeps metadata single line", () => { using var b=new Bitmap(420,120);using(var g=Graphics.FromImage(b))g.Clear(Color.FromArgb(50,50,50));var button=L("BTN",new(20,20,160,60),"Continue");button.RoleType=RegionRoleType.Button;button.TranslationText="继续";var meta=L("META",new(220,20,160,40),"5 days ago");meta.RoleType=RegionRoleType.Metadata;meta.TranslationText="5天前";var x=RegionRendererV2.Render(b,[button,meta],new RenderSettings());using var image=x.Bitmap;var ds=x.Diagnostics!;var bd=ds.Single(d=>d.RegionId=="BTN");var md=ds.Single(d=>d.RegionId=="META");Assert(bd.RenderedLines[0].Bounds.X>button.BoundingBox.Left&&md.LineCount==1,"role layout"); });
        Test("Renderer 2 long translation is never ellipsized", () => { using var b=new Bitmap(240,80);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("LONG",new(5,5,225,65),"source");r.TranslationText=new string('中',100);var x=RegionRendererV2.Render(b,[r],new RenderSettings());using var image=x.Bitmap;var d=x.Diagnostics!.Single();var drawn=string.Concat(d.RenderedLines.Select(l=>l.Text));Assert((drawn==r.TranslationText&&!d.RenderedLines.Any(l=>l.Text.Contains('…')))||(!d.AtomicRegionCommitted&&BitmapPixelsEqual(b,image)),"translation clipped or partially committed"); });
        Test("Renderer 2 mixed text remains intact", () => { using var b=new Bitmap(360,100);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("MIX",new(10,10,330,80),"source");r.TranslationText="TikTok: 33M，Instagram: 77M，OnlyFans: 0";var x=RegionRendererV2.Render(b,[r],new RenderSettings());using var image=x.Bitmap;Assert(string.Concat(x.Diagnostics!.Single().RenderedLines.Select(l=>l.Text))==r.TranslationText,"mixed text changed"); });
        Test("Renderer 2 preserved original has explicit status", () => { using var b=new Bitmap(160,60);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("KEEP",new(10,10,120,30),"@imsober");r.PreserveOriginal=true;r.TranslationText="@imsober";var x=RegionRendererV2.Render(b,[r],new RenderSettings());using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(d.RenderStatus==RegionRenderStatus.PreservedOriginal&&!d.Coverage.Any(c=>c.Masked),"preserve decision"); });
        Test("Renderer 2 safe expansion respects neighbor collision", () => { using var b=new Bitmap(220,80);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var a=L("A",new(5,5,100,65),"a");var c=L("B",new(110,5,100,65),"b");a.TranslationText=new string('中',80);c.TranslationText="第二块";var x=RegionRendererV2.Render(b,[a,c],new RenderSettings());using var image=x.Bitmap;var ad=x.Diagnostics!.Single(d=>d.RegionId=="A");Assert(ad.RenderedLines.All(l=>l.Bounds.Right<=a.BoundingBox.Right+1),"expanded into neighbor"); });
        Test("Readable fallback commits full translation with mask-local cleanup", () => { using var b=new Bitmap(360,110);using(var g=Graphics.FromImage(b)){g.Clear(Color.FromArgb(35,45,55));using var f=new Font("Arial",18);g.DrawString("SOURCE GLYPHS",f,Brushes.White,new PointF(12,35));}var r=L("FB",new(10,20,210,55),"SOURCE GLYPHS");r.RoleType=RegionRoleType.CharacterName;r.SourceLinePolygons=[GeometryV2.RectanglePolygon(new RectangleF(10,20,210,55))];r.TranslationText="这是必须完整显示的较长译文";var neighbor=L("N",new(285,20,60,55),"KEEP");neighbor.PreserveOriginal=true;neighbor.TranslationText="KEEP";var x=RegionRendererV2.Render(b,[r,neighbor],new RenderSettings{Outline=false,Shadow=false,MinFontSize=10});using var image=x.Bitmap;var d=x.Diagnostics!.Single(v=>v.RegionId=="FB");var drawn=string.Concat(d.RenderedLines.Select(v=>v.Text));Assert(d.AtomicRegionCommitted&&d.DecisionCode=="VisibleTranslationCommitted"&&d.Alpha==0&&drawn==r.TranslationText&&d.Coverage.All(v=>v.Masked&&v.Decision=="ReadableFallbackCleanupMask")&&RectangleF.Intersect(d.RenderBounds,neighbor.BoundingBox).IsEmpty,$"fallback did not provide an ownership-safe visible commit: status={d.RenderStatus}, code={d.DecisionCode}, alpha={d.Alpha}, drawn={drawn.Length}/{r.TranslationText.Length}, bounds={d.RenderBounds}"); });
        Test("Preview placement remains visible after monitor change", () => { var normalized=PreviewWindowPlacementPolicy.Normalize(new(4000,200,1200,800),[new(0,0,1920,1040)],new(820,560));Assert(new Rectangle(0,0,1920,1040).Contains(normalized),"off-screen restore"); });
        Test("First and second preview preserve minimized main window", () => { using var main=new Form { WindowState=FormWindowState.Minimized }; using var first=new Form();WindowStateGuard.ShowPreviewWithoutRestoringMain(main,first);Assert(main.WindowState==FormWindowState.Minimized,"first capture restored main");first.Close();using var second=new Form();WindowStateGuard.ShowPreviewWithoutRestoringMain(main,second);Assert(main.WindowState==FormWindowState.Minimized,"second capture restored main");second.Close(); });
        Test("Coverage accounts for every OCR SourceLine", () => { var blocks=Enumerable.Range(1,10).Select(i=>new OcrEngineBlock{Id=$"L{i}",RawText=$"line {i}",CorrectedText=$"line {i}",BoundingBox=new(10,i*12,100,10),Polygon=GeometryV2.RectanglePolygon(new(10,i*12,100,10)),Enabled=true,ReadingOrder=i}).ToArray();var regions=blocks.Select(b=>L(b.Id,b.BoundingBox,b.RawText)).ToList();var c=RecognitionCoverageFinalizer.Finalize(regions,blocks,new(200,200),1).Coverage;Assert(c.Count==10&&c.All(x=>x.Disposition==SourceLineDisposition.AssignedToTranslationUnit),"unaccounted source line"); });
        Test("Coverage preserves eight merged paragraph polygons", () => { var blocks=Enumerable.Range(1,8).Select(i=>new OcrEngineBlock{Id=$"L{i}",RawText=$"line {i}",CorrectedText=$"line {i}",BoundingBox=new(10,i*12,120,10),Polygon=GeometryV2.RectanglePolygon(new(10,i*12,120,10)),Enabled=true,ReadingOrder=i}).ToArray();var merged=SemanticRegionGrouperV2.Group(blocks.Select(b=>L(b.Id,b.BoundingBox,b.RawText)).ToArray(),1);RecognitionCoverageFinalizer.Finalize(merged,blocks,new(200,200),1);Assert(merged.Count==1&&merged[0].SourceBlockIds.Count==8&&merged[0].SourceLinePolygons.Count==8,"merged geometry lost"); });
        Test("Residual tail uses conservative compatible ownership", () => { var blocks=Enumerable.Range(1,8).Select(i=>new OcrEngineBlock{Id=$"L{i}",RawText=$"line {i}",CorrectedText=$"line {i}",BoundingBox=new(10,i*12,120,10),Polygon=GeometryV2.RectanglePolygon(new(10,i*12,120,10)),Enabled=true,ReadingOrder=i}).ToArray();var owner=R("P",new(10,12,120,82));owner.RoleType=RegionRoleType.BodyParagraph;owner.DetectedBlocks=blocks.Take(7).ToList();var regions=new List<RecognitionRegion>{owner};RecognitionCoverageFinalizer.Finalize(regions,blocks,new(200,200),1);Assert(regions.Single().SourceBlockIds.Count==8,"tail not assigned"); });
        Test("Residual does not cross into protected metadata", () => { var body=L("B",new(10,10,160,40),"body");body.RoleType=RegionRoleType.BodyParagraph;var meta=L("M",new(10,70,160,16),"5 days ago");meta.RoleType=RegionRoleType.Metadata;var tail=new OcrEngineBlock{Id="T",RawText="tail",CorrectedText="tail",BoundingBox=new(10,52,160,12),Polygon=GeometryV2.RectanglePolygon(new(10,52,160,12)),Enabled=true};var regions=new List<RecognitionRegion>{body,meta};RecognitionCoverageFinalizer.Finalize(regions,body.DetectedBlocks.Concat(meta.DetectedBlocks).Append(tail).ToArray(),new(220,120),1);Assert(regions.Single(x=>x.RegionId==body.RegionId).SourceBlockIds.Contains("T")&&!regions.Single(x=>x.RegionId==meta.RegionId).SourceBlockIds.Contains("T"),"nearest metadata captured residual"); });
        Test("Preserved username has explicit disposition", () => { var r=L("U",new(5,5,80,15),"@imsober");r.PreserveOriginal=true;var regions=new List<RecognitionRegion>{r};var c=RecognitionCoverageFinalizer.Finalize(regions,r.DetectedBlocks,new(100,40),1).Coverage.Single();Assert(c.Disposition==SourceLineDisposition.PreserveOriginal,"preserve missing"); });
        Test("Ignored noise has reason and remains accounted", () => { var b=new OcrEngineBlock{Id="N",RawText=".",CorrectedText=".",BoundingBox=new(5,5,4,4),Polygon=GeometryV2.RectanglePolygon(new(5,5,4,4)),Enabled=true,SuspectedFalsePositive=true};var regions=new List<RecognitionRegion>();var c=RecognitionCoverageFinalizer.Finalize(regions,[b],new(40,40),1).Coverage.Single();Assert(c.Disposition==SourceLineDisposition.IgnoredWithReason&&!string.IsNullOrWhiteSpace(c.Reason),"ignored without reason"); });
        Test("Missing polygon fails required geometry validation", () => { var b=new OcrEngineBlock{Id="X",RawText="translate",CorrectedText="translate",BoundingBox=RectangleF.Empty,Enabled=true};var regions=new List<RecognitionRegion>();var finalized=RecognitionCoverageFinalizer.Finalize(regions,[b],new(100,100),1);var d=new RecognitionDocumentV2();d.Regions.AddRange(regions);d.SourceLineCoverage.AddRange(finalized.Coverage);d.TranslationUnits.AddRange(TranslationUnitBuilderV2.Build(regions));d.CoverageSummary=RecognitionCoverageFinalizer.BindTranslationUnits(d);Assert(RecognitionCoverageValidator.Validate(d).Any(x=>x.Contains("Missing required geometry")),"missing polygon accepted"); });
        Test("BoundingRect fallback stays line-local", () => { var b=new OcrEngineBlock{Id="R",RawText="line",CorrectedText="line",BoundingBox=new(20,20,30,10),Polygon=[],Enabled=true};var regions=new List<RecognitionRegion>();var c=RecognitionCoverageFinalizer.Finalize(regions,[b],new(200,100),1).Coverage.Single();Assert(c.UsedBoundingRectFallback&&GeometryV2.Bounds(c.Polygon)==b.BoundingBox,"rect fallback expanded"); });
        Test("Duplicate text at different positions keeps two identities", () => { var a=new OcrEngineBlock{Id="A",RawText="Continue",CorrectedText="Continue",BoundingBox=new(5,5,60,20),Polygon=GeometryV2.RectanglePolygon(new(5,5,60,20)),Enabled=true};var b=new OcrEngineBlock{Id="B",RawText="Continue",CorrectedText="Continue",BoundingBox=new(100,5,60,20),Polygon=GeometryV2.RectanglePolygon(new(100,5,60,20)),Enabled=true};var regions=new List<RecognitionRegion>();var c=RecognitionCoverageFinalizer.Finalize(regions,[a,b],new(200,60),1).Coverage;Assert(c.Select(x=>x.SourceLineId).SequenceEqual(["A","B"])&&c.Select(x=>GeometryV2.Bounds(x.Polygon).X).Distinct().Count()==2,"text dedup lost geometry"); });
        Test("FollowPrevious strictly inherits last normal size",()=>Assert(PreviewSizingPolicy.Resolve(PreviewWindowSizingMode.FollowPrevious,new(300,200),new(1920,1080),new(1220,800),new(1500,900),new(820,560))==new Size(1500,900),"previous size not inherited"));
        Test("Fixed preview remains exact",()=>Assert(PreviewSizingPolicy.Resolve(PreviewWindowSizingMode.Fixed,new(3000,2000),new(1920,1080),new(1220,800),new(1500,900),new(820,560))==new Size(1220,800),"fixed changed"));
        Test("Automatic preview is image and work-area aware",()=>{var a=PreviewSizingPolicy.Resolve(PreviewWindowSizingMode.CurrentAuto,new(500,1500),new(1920,1080),new(),new(),new(820,560));var b=PreviewSizingPolicy.Resolve(PreviewWindowSizingMode.CurrentAuto,new(1500,500),new(1920,1080),new(),new(),new(820,560));Assert(a!=b&&a.Width<=1728&&b.Width<=1728,"automatic sizing static");});
        Test("Capture restore policy does not steal foreground",()=>Assert(!CaptureForegroundPolicy.ShouldReactivate(false),"background main reactivated"));
        Test("Missing font falls back safely",()=>Assert(FontSettingsPolicy.ResolveFamily("__missing__","Microsoft YaHei UI")=="Microsoft YaHei UI","fallback failed"));
        Test("Translation style display mapping is Chinese",()=>Assert(UiStrings.TranslationStyleName(TranslationStyle.Natural)=="自然"&&UiStrings.TranslationStyleName(TranslationStyle.GameLocalization)=="游戏本地化","style not localized"));
        Test("Source language display mapping is Chinese",()=>Assert(Enum.GetValues<SourceLanguageMode>().Select(UiStrings.SourceLanguageName).SequenceEqual(["自动识别","英语","简体中文","日语","韩语","混合语言"]),"source language leaked enum"));
        Test("Target language UI mapping is Chinese and code stable",()=>Assert(UiTargetLanguageDisplay.DisplayFromCode("en")=="英语"&&UiTargetLanguageDisplay.CodeFromDisplay("日语")=="ja"&&TargetLanguageDisplay.DisplayFromCode("en")=="English","target UI mapping changed compatibility layer"));
        Test("Preview and background display mappings are Chinese",()=>Assert(UiStrings.PreviewSizeModeName(PreviewWindowSizingMode.FollowPrevious)=="沿用上次"&&UiStrings.BackgroundStyleName(TranslationOverlayBackgroundStyle.LightOverlay)=="半透明底板","display mapping"));
        Test("Disabled setting label remains legible",()=>{var c=MainForm.DisabledSettingLabelColor;Assert(c.R>=150&&c.G>=150&&c.B>=150,"disabled label too dark");});
        Test("Standard button resources are valid Chinese",()=>Assert(UiStrings.Ok=="确定"&&UiStrings.Cancel=="取消"&&UiStrings.Apply=="应用"&&UiStrings.ResetDefaults=="恢复默认","button mojibake"));
        Test("Appearance settings persist in snapshot",()=>{var s=new ApiSettings{PreviewWindowSizingMode=PreviewWindowSizingMode.Fixed,UiFontMode=UiFontMode.Custom,UiFontFamily="Segoe UI",OverlayBackgroundStyle=TranslationOverlayBackgroundStyle.Solid,OverlayBackgroundOpacity=180};var c=ApiSettingsSnapshot.Copy(s);Assert(c.PreviewWindowSizingMode==s.PreviewWindowSizingMode&&c.UiFontFamily=="Segoe UI"&&c.OverlayBackgroundStyle==TranslationOverlayBackgroundStyle.Solid&&c.OverlayBackgroundOpacity==180,"appearance lost");});
        Test("FollowPrevious maximized state persists",()=>{var s=new ApiSettings{PreviewWindowSizingMode=PreviewWindowSizingMode.FollowPrevious,HasPreviewWindowPlacement=true,PreviewWindowX=40,PreviewWindowY=50,PreviewWindowWidth=1400,PreviewWindowHeight=900,PreviewWindowMaximized=true};var c=ApiSettingsSnapshot.Copy(s);Assert(c.HasPreviewWindowPlacement&&c.PreviewWindowMaximized&&c.PreviewWindowWidth==1400&&c.PreviewWindowHeight==900,"maximized placement lost");});
        Test("FollowPrevious saves live bounds before close",()=>{using var image=new Bitmap(200,100);PreviewWindowPlacement? saved=null;var ocr=new OcrRuntimeManager(AppContext.BaseDirectory,new OcrService());var vision=new VisionRuntimeManager(AppContext.BaseDirectory);try{using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{PreviewWindowSizingMode=PreviewWindowSizingMode.FollowPrevious},new OcrService(),new TranslationService(),ocr,vision,new SessionServices(),x=>saved=x);form.Bounds=new(70,80,1380,860);form.SavePlacementForSmoke();Assert(saved is {X:70,Y:80,Width:1380,Height:860,Maximized:false},"live bounds not saved");}finally{vision.DisposeAsync().AsTask().GetAwaiter().GetResult();ocr.DisposeAsync().AsTask().GetAwaiter().GetResult();}});
        Test("Preview size mode runtime transition matrix",()=>{using var image=new Bitmap(500,300);using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());foreach(var mode in new[]{PreviewWindowSizingMode.Fixed,PreviewWindowSizingMode.FollowPrevious,PreviewWindowSizingMode.CurrentAuto,PreviewWindowSizingMode.FollowPrevious,PreviewWindowSizingMode.Fixed,PreviewWindowSizingMode.FollowPrevious}){form.ApplyPreviewWindowSettings(new ApiSettings{PreviewWindowSizingMode=mode,FixedPreviewWidth=1220,FixedPreviewHeight=800},true);Assert(form.PreviewSizingModeForSmoke==mode,$"mode stuck at {form.PreviewSizingModeForSmoke}");}});
        Test("Fixed to FollowPrevious saves new user bounds",()=>{using var image=new Bitmap(200,100);PreviewWindowPlacement? saved=null;var ocr=new OcrRuntimeManager(AppContext.BaseDirectory,new OcrService());var vision=new VisionRuntimeManager(AppContext.BaseDirectory);try{using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{PreviewWindowSizingMode=PreviewWindowSizingMode.Fixed,FixedPreviewWidth=1220,FixedPreviewHeight=800},new OcrService(),new TranslationService(),ocr,vision,new SessionServices(),x=>saved=x);form.SavePlacementForSmoke();Assert(saved is null,"fixed polluted last bounds");form.ApplyPreviewWindowSettings(new ApiSettings{PreviewWindowSizingMode=PreviewWindowSizingMode.FollowPrevious},false);form.Bounds=new(80,90,1500,900);form.SavePlacementForSmoke();Assert(saved is {Width:1500,Height:900},"follow did not capture new user bounds");}finally{vision.DisposeAsync().AsTask().GetAwaiter().GetResult();ocr.DisposeAsync().AsTask().GetAwaiter().GetResult();}});
        Test("FollowPrevious maximized survives mode switch",()=>{using var image=new Bitmap(200,100);using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{PreviewWindowSizingMode=PreviewWindowSizingMode.Fixed,VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());form.ApplyPreviewWindowSettings(new ApiSettings{PreviewWindowSizingMode=PreviewWindowSizingMode.FollowPrevious,HasPreviewWindowPlacement=true,PreviewWindowX=20,PreviewWindowY=20,PreviewWindowWidth=1300,PreviewWindowHeight=850,PreviewWindowMaximized=true},true);Assert(form.PreviewSizingModeForSmoke==PreviewWindowSizingMode.FollowPrevious&&form.WindowState==FormWindowState.Maximized,"maximize lost after switch");});
        Test("Appearance change never starts OCR or translation",()=>{using var image=new Bitmap(200,100);using var form=new PreviewForm(image,PreviewMode.OcrOnly,new ApiSettings{VisualModel=VisualModelKind.Off},new OcrService(),new TranslationService());var recognition=form.RecognitionRunCountForSmoke;var translation=form.TranslationGenerationForSmoke;form.ApplyAppearanceSettings(new ApiSettings{OverlayFontMode=OverlayFontMode.Custom,OverlayFontFamily="SimSun",OverlayBackgroundStyle=TranslationOverlayBackgroundStyle.LightOverlay,OverlayBackgroundOpacity=180});Assert(form.RecognitionRunCountForSmoke==recognition&&form.TranslationGenerationForSmoke==translation&&form.ActiveTranslationOperationsForSmoke==0,"appearance triggered pipeline");});
        Test("Legacy settings load with new safe defaults",()=>{var p=Path.Combine(Path.GetTempPath(),$"st-legacy-{Guid.NewGuid():N}.json");try{File.WriteAllText(p,"{\"SettingsSchemaVersion\":8,\"TargetLanguage\":\"Japanese\"}");var s=ConfigurationManager.Load(p,false);Assert(s.TargetLanguage=="Japanese"&&s.PreviewWindowSizingMode==PreviewWindowSizingMode.CurrentAuto&&s.OverlayBackgroundStyle==TranslationOverlayBackgroundStyle.Automatic,"legacy defaults invalid");}finally{if(File.Exists(p))File.Delete(p);if(File.Exists(p+".bak"))File.Delete(p+".bak");}});
        Test("Background strategies produce distinct runtime settings",()=>{var a=new RenderSettings();FontSettingsPolicy.ApplyOverlay(a,new ApiSettings{OverlayBackgroundStyle=TranslationOverlayBackgroundStyle.Automatic});var l=new RenderSettings();FontSettingsPolicy.ApplyOverlay(l,new ApiSettings{OverlayBackgroundStyle=TranslationOverlayBackgroundStyle.LightOverlay,OverlayBackgroundOpacity=40});var s=new RenderSettings();FontSettingsPolicy.ApplyOverlay(s,new ApiSettings{OverlayBackgroundStyle=TranslationOverlayBackgroundStyle.Solid});Assert(!a.Background&&l.Background&&l.BackgroundOpacity==40&&s.BackgroundOpacity==255,"strategy runtime ignored");});
        Test("Background alpha diagnostics identify normal or fallback path",()=>{using var b=new Bitmap(240,100);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("A",new(10,10,200,70),"source");r.TranslationText="中文背景透明度测试";var x=RegionRendererV2.Render(b,[r],new RenderSettings{BackgroundStrategy=TranslationOverlayBackgroundStyle.LightOverlay,BackgroundOpacity=180});using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert((d.BackgroundStrategy=="LightOverlay"&&d.Alpha==180)||(d.BackgroundStrategy=="ReadableFallbackBackgroundPreserving"&&d.Alpha==0),"effective alpha path not explicit");});
        Test("Background alpha changes rendered pixels",()=>{using var b=new Bitmap(260,110);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("A",new(10,10,220,80),"source");r.TranslationText="透明度像素测试";var low=RegionRendererV2.Render(b,[r],new RenderSettings{BackgroundStrategy=TranslationOverlayBackgroundStyle.LightOverlay,BackgroundOpacity=40});var high=RegionRendererV2.Render(b,[r],new RenderSettings{BackgroundStrategy=TranslationOverlayBackgroundStyle.LightOverlay,BackgroundOpacity=180});using var li=low.Bitmap;using var hi=high.Bitmap;var rr=low.TranslationRenderRects!["A"];var p=new Point((int)rr.Left+2,(int)rr.Top+2);Assert(li.GetPixel(p.X,p.Y).ToArgb()!=hi.GetPixel(p.X,p.Y).ToArgb(),"alpha did not change pixels");});
        Test("Renderer effective background path has no blur coupling",()=>{using var b=new Bitmap(260,110);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("A",new(10,10,220,80),"source");r.TranslationText="Alpha 不等于模糊";var x=RegionRendererV2.Render(b,[r],new RenderSettings{BackgroundStrategy=TranslationOverlayBackgroundStyle.LightOverlay,BackgroundOpacity=120});using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(d.BlurRadius==0&&(d.Alpha==120||d.Alpha==0),"effective alpha coupled to blur");});
        Test("Renderer draws at original pixel resolution",()=>{using var b=new Bitmap(777,333);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("A",new(20,20,400,100),"source");r.TranslationText="最终像素直接绘制";var x=RegionRendererV2.Render(b,[r],new RenderSettings());using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(image.Size==b.Size&&d.RenderedLines.All(l=>l.Bounds.X==MathF.Round(l.Bounds.X)&&l.Bounds.Y==MathF.Round(l.Bounds.Y)),"scaled or half-pixel text draw");});
        Test("Background strategies change rendered output",()=>{using var b=new Bitmap(260,110);using(var g=Graphics.FromImage(b))g.Clear(Color.FromArgb(220,220,220));var r=L("A",new(10,10,220,80),"source");r.TranslationText="背景策略测试";var auto=RegionRendererV2.Render(b,[r],new RenderSettings{BackgroundStrategy=TranslationOverlayBackgroundStyle.Automatic});var solid=RegionRendererV2.Render(b,[r],new RenderSettings{BackgroundStrategy=TranslationOverlayBackgroundStyle.Solid,BackgroundOpacity=255});using var ai=auto.Bitmap;using var si=solid.Bitmap;var rr=solid.TranslationRenderRects!["A"];var p=new Point((int)rr.Left+2,(int)rr.Top+2);Assert(ai.GetPixel(p.X,p.Y).ToArgb()!=si.GetPixel(p.X,p.Y).ToArgb(),"strategy output identical");});
        Test("Overlay font changes actual render metrics",()=>{using var b=new Bitmap(360,130);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("A",new(10,10,320,100),"source");r.TranslationText="字体切换 ABC 123 测试";var alternate=FontSettingsPolicy.IsInstalled("Segoe UI")?"Segoe UI":FontSettingsPolicy.Families().First(x=>!x.Equals("Microsoft YaHei UI",StringComparison.OrdinalIgnoreCase));var a=RegionRendererV2.Render(b,[r],new RenderSettings{FontFamily="Microsoft YaHei UI",FontScale=1.2f});var s=RegionRendererV2.Render(b,[r],new RenderSettings{FontFamily=alternate,FontScale=1.2f});using var ai=a.Bitmap;using var si=s.Bitmap;var ad=a.Diagnostics!.Single();var sd=s.Diagnostics!.Single();Assert(ad.FontFamily!=sd.FontFamily&&(ad.RenderBounds!=sd.RenderBounds||!BitmapPixelsEqual(ai,si)),"font did not affect rendering");});
        Test("Tight translation bounds do not fill semantic region",()=>{using var b=new Bitmap(500,250);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("T",new(10,10,450,200),"source");r.TranslationText="短译文";var x=RegionRendererV2.Render(b,[r],new RenderSettings{BackgroundStrategy=TranslationOverlayBackgroundStyle.Solid});using var image=x.Bitmap;var rr=x.TranslationRenderRects!["T"];Assert(rr.Height<r.BoundingBox.Height*.6f,"large card background remained");});
        Test("Original and translated display rect stay separate",()=>{var r=R("R",new(1,2,30,20));r.TranslationRenderRect=new(10,12,44,26);Assert(RegionDisplayMapping.Resolve(r,ImageViewMode.Original)==r.BoundingBox&&RegionDisplayMapping.Resolve(r,ImageViewMode.Translated)==r.TranslationRenderRect,"rect mapping merged");});
        Test("Five-preview highlight mapping remains isolated",()=>{for(var i=0;i<5;i++){var r=R($"P{i}",new(i*10,2,30,20));r.TranslationRenderRect=new(100+i*20,12,44,26);Assert(RegionDisplayMapping.Resolve(r,ImageViewMode.Original)==r.BoundingBox&&RegionDisplayMapping.Resolve(r,ImageViewMode.Translated)==r.TranslationRenderRect,$"preview {i} reused old rect");}});
        Test("Empty translation has no translated rect",()=>{var r=R("R",new(1,2,30,20));Assert(RegionDisplayMapping.Resolve(r,ImageViewMode.Translated)is null,"source rect leaked" );});
        Test("Renderer diagnostics include font and render bounds",()=>{using var b=new Bitmap(260,100);using(var g=Graphics.FromImage(b))g.Clear(Color.White);var r=L("D",new(10,10,220,70),"source");r.TranslationText="诊断字段";var x=RegionRendererV2.Render(b,[r],new RenderSettings{FontFamily="Microsoft YaHei UI"});using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(!string.IsNullOrWhiteSpace(d.FontFamily)&&!d.RenderBounds.IsEmpty&&d.TranslationRenderRect is not null,"diagnostics incomplete");});
        Test("Small artwork caption keeps complete translation in owned bounds",()=>{using var b=new Bitmap(640,360);using(var g=Graphics.FromImage(b)){g.Clear(Color.FromArgb(42,24,80));g.FillRectangle(new SolidBrush(Color.FromArgb(70,42,120)),35,79,180,20);}var r=L("CAP",new(35,79,180,20),"Your mean ex is back in your life");r.RoleType=RegionRoleType.BodyParagraph;r.TranslationText="你那个刻薄的前女友又回到了你的生活里";r.LayoutExclusionPolygons=[GeometryV2.RectanglePolygon(new RectangleF(240,60,120,90))];var x=RegionRendererV2.Render(b,[r],new RenderSettings{FontFamily="Microsoft YaHei UI"});using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(d.AtomicRegionCommitted&&d.TextDrawCount==1&&d.FallbackRendered,"small caption was not committed");Assert(string.Concat(d.RenderedLines.Select(y=>y.Text))==r.TranslationText,"small caption translation changed");Assert(d.FontSize>=6&&d.FinalRenderBounds==r.BoundingBox,"caption escaped ownership or became unreadable");});
        Test("Normal label retains standard readable floor",()=>{using var b=new Bitmap(320,100);using(var g=Graphics.FromImage(b))g.Clear(Color.FromArgb(30,30,30));var r=L("LABEL",new(20,20,180,24),"Continue");r.RoleType=RegionRoleType.UILabel;r.TranslationText="继续";var x=RegionRendererV2.Render(b,[r],new RenderSettings{FontFamily="Microsoft YaHei UI"});using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(!d.AtomicRegionCommitted||d.FontSize>=8,"normal label used caption-only floor");});
        Test("Long body never uses compact caption floor",()=>{using var b=new Bitmap(500,220);using(var g=Graphics.FromImage(b))g.Clear(Color.FromArgb(38,38,42));var r=L("BODY",new(20,20,420,120),"A long paragraph source");r.RoleType=RegionRoleType.BodyParagraph;r.TranslationText="这是一段需要保持正文可读字号的长文本，用于确认小字幕规则不会影响普通正文段落。";var x=RegionRendererV2.Render(b,[r],new RenderSettings{FontFamily="Microsoft YaHei UI"});using var image=x.Bitmap;var d=x.Diagnostics!.Single();Assert(!d.AtomicRegionCommitted||d.FontSize>=10,"long body used compact caption floor");});
        Test("Artwork caption respects adjacent region reservation",()=>{using var b=new Bitmap(640,360);using(var g=Graphics.FromImage(b))g.Clear(Color.FromArgb(45,30,85));var r=L("CAP",new(35,79,180,20),"caption");r.RoleType=RegionRoleType.BodyParagraph;r.TranslationText="你那个刻薄的前女友又回到了你的生活里";var neighbor=L("NEIGHBOR",new(220,70,120,44),"dialogue");neighbor.RoleType=RegionRoleType.Dialogue;neighbor.PreserveOriginal=true;var x=RegionRendererV2.Render(b,[r,neighbor],new RenderSettings{FontFamily="Microsoft YaHei UI"});using var image=x.Bitmap;var d=x.Diagnostics!.Single(y=>y.RegionId=="CAP");Assert(d.AtomicRegionCommitted&&RectangleF.Intersect(d.FinalRenderBounds,neighbor.BoundingBox).IsEmpty,"caption crossed adjacent region");});
        Test("Unsafe oversized caption fails without foreign commit",()=>{using var b=new Bitmap(640,360);using(var g=Graphics.FromImage(b))g.Clear(Color.FromArgb(45,30,85));var r=L("CAP",new(35,79,80,12),"caption");r.RoleType=RegionRoleType.BodyParagraph;r.TranslationText=new string('译',120);var neighbor=L("NEIGHBOR",new(120,70,120,44),"dialogue");neighbor.RoleType=RegionRoleType.Dialogue;neighbor.PreserveOriginal=true;var x=RegionRendererV2.Render(b,[r,neighbor],new RenderSettings{FontFamily="Microsoft YaHei UI"});using var image=x.Bitmap;var d=x.Diagnostics!.Single(y=>y.RegionId=="CAP");Assert(!d.AtomicRegionCommitted&&d.TextDrawCount==0,"unsafe caption committed partial text");});

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
        File.WriteAllLines(outputPath, results.Concat([$"TOTAL={pass + fail} PASS={pass} FAIL={fail}", "REAL_API_CALLS=0", "ActiveOperations=0", "Worker residue=NONE"]));
        return fail == 0 ? 0 : 2;
    }

    private static bool BitmapPixelsEqual(Bitmap a, Bitmap b)
    {
        if (a.Size != b.Size) return false;
        for (var y = 0; y < a.Height; y += 2)
            for (var x = 0; x < a.Width; x += 2)
                if (a.GetPixel(x, y).ToArgb() != b.GetPixel(x, y).ToArgb()) return false;
        return true;
    }
    private static bool BitmapPixelsEqualExact(Bitmap a, Bitmap b)
    {
        if (a.Size != b.Size) return false;
        for (var y=0;y<a.Height;y++) for(var x=0;x<a.Width;x++) if(a.GetPixel(x,y).ToArgb()!=b.GetPixel(x,y).ToArgb()) return false;
        return true;
    }
}
