<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>游戏翻译器</AssemblyName>
    <RootNamespace>GameTranslatorManager</RootNamespace>
    <Version>0.4.0.0</Version>
    <AssemblyVersion>0.4.0.0</AssemblyVersion>
    <FileVersion>0.4.0.0</FileVersion>
    <InformationalVersion>0.4.0-test</InformationalVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <EmbeddedResource
      Include="payloads\UnityMono.zip"
      LogicalName="GameTranslatorManager.Payloads.UnityMono.zip" />
  </ItemGroup>
</Project>
