"""Build the embedded archive and its C# integrity table. No installation or execution."""
from pathlib import Path
import hashlib, json, zipfile

SOURCE = Path(__file__).resolve().parents[2]
WORK = SOURCE.parent
ROOT = WORK.parent.parent
assert WORK.name == "CloudMeadow-0.6.0.21" and SOURCE.name == "Source"
PLUGIN = "BepInEx/plugins/CloudMeadowTranslator/CloudMeadowTranslator.dll"
CONFIG = "BepInEx/config/local.codex.cloudmeadow.translator.cfg"
DLL = ROOT / "Build/CloudMeadow-0.6.0.21/CloudMeadowTranslator.dll"
FONT = Path(__file__).parent / "FontAssets"
OUT = SOURCE / "Plugin/Payload/CloudMeadow.zip"
files = {}
with zipfile.ZipFile(SOURCE / "Plugin/Payload/UnityMono.zip") as z:
    for name in z.namelist():
        if not name.endswith("/") and (name.startswith("BepInEx/core/") or name in (".doorstop_version", "doorstop_config.ini", "winhttp.dll", "changelog.txt")):
            files[name] = z.read(name)
files[PLUGIN] = DLL.read_bytes()
for path in sorted(FONT.iterdir()):
    if path.is_file():
        files["BepInEx/plugins/CloudMeadowTranslator/FontAssets/" + path.name] = path.read_bytes()
assert all("MGITranslator" not in n and not n.endswith(".cfg") for n in files)
hashes = {n: hashlib.sha256(data).hexdigest().upper() for n, data in sorted(files.items())}
with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for name, data in sorted(files.items()):
        info = zipfile.ZipInfo(name, (2026, 9, 14, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        z.writestr(info, data)
code = '''// Generated by Source/Plugin/CloudMeadow/package-payload.py; do not hand-edit hashes.
namespace ScreenshotTranslationUiTester;
internal static class FusionCloudPayload
{
    internal const string Plugin = "%s";
    internal const string Config = "%s";
    internal const string PluginVersion = "0.6.0.21";
    internal const string PluginSha256 = "%s";
    internal static readonly IReadOnlyDictionary<string,string> Files = new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
    {
%s
    };
}
''' % (PLUGIN, CONFIG, hashes[PLUGIN], "\n".join('        ["%s"] = "%s",' % (n,h) for n,h in hashes.items()))
(SOURCE / "Screenshot/FusionCloudPayload.cs").write_text(code, encoding="utf-8")
report = {"status":"built-not-runtime-tested", "source":str(SOURCE), "pluginVersion":"0.6.0.21", "pluginSha256":hashes[PLUGIN], "archiveSha256":hashlib.sha256(OUT.read_bytes()).hexdigest().upper(), "files":hashes}
(WORK / "Static/payload-manifest.json").write_text(json.dumps(report,indent=2),encoding="utf-8")
print(f"Cloud payload packaged: {len(files)} files, {OUT.stat().st_size} bytes; plugin SHA256 {hashes[PLUGIN]}")
